# SPDX-License-Identifier: GPL-3.0-or-later
# Explicit opt-in: archives may not be the revisions pinned in cpmfile.json.
# Do not enable for a release build without reviewing the local revisions and
# the cpmfile patches: CPM's existing CUSTOM_DIR path assumes pre-prepared code.
include_guard(GLOBAL)
set(SUYU_LOCAL_EXTERNALS_ROOT "${CMAKE_SOURCE_DIR}/externals" CACHE PATH
    "Root containing locally populated dependency source trees")
if(NOT IS_DIRECTORY "${SUYU_LOCAL_EXTERNALS_ROOT}")
    message(FATAL_ERROR "Local dependency root not found: ${SUYU_LOCAL_EXTERNALS_ROOT}")
endif()
set(_local_roots "${SUYU_LOCAL_EXTERNALS_ROOT}"
    "${SUYU_LOCAL_EXTERNALS_ROOT}/dynarmic/externals"
    "${SUYU_LOCAL_EXTERNALS_ROOT}/sirit/externals")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../cpmfile.json" _local_packages)
string(JSON _local_count LENGTH "${_local_packages}")
math(EXPR _local_last "${_local_count}-1")
set(_local_report "Local custom dependency sources; pinned revisions and repository patches are NOT implied.\n")
foreach(_local_index RANGE ${_local_last})
    string(JSON _local_key MEMBER "${_local_packages}" ${_local_index})
    string(JSON _local_ci ERROR_VARIABLE _local_no_ci GET "${_local_packages}" "${_local_key}" ci)
    if(NOT _local_no_ci AND _local_ci)
        continue() # Binary CI artifacts are not interchangeable with source trees.
    endif()
    string(JSON _local_repo ERROR_VARIABLE _local_no_repo GET "${_local_packages}" "${_local_key}" repo)
    if(_local_no_repo)
        continue()
    endif()
    string(JSON _local_name ERROR_VARIABLE _local_no_name GET "${_local_packages}" "${_local_key}" package)
    if(_local_no_name)
        set(_local_name "${_local_key}")
    endif()
    if(DEFINED ${_local_name}_CUSTOM_DIR AND NOT "${${_local_name}_CUSTOM_DIR}" STREQUAL "")
        string(APPEND _local_report "${_local_name}: ${${_local_name}_CUSTOM_DIR} (explicit override)\n")
        continue()
    endif()
    get_filename_component(_local_basename "${_local_repo}" NAME)
    set(_local_candidates)
    foreach(_local_root IN LISTS _local_roots)
        list(APPEND _local_candidates "${_local_root}/${_local_basename}"
            "${_local_root}/${_local_key}" "${_local_root}/${_local_name}")
    endforeach()
    if(_local_key STREQUAL "ffmpeg")
        list(PREPEND _local_candidates "${SUYU_LOCAL_EXTERNALS_ROOT}/ffmpeg/ffmpeg")
    elseif(_local_key STREQUAL "libusb")
        list(PREPEND _local_candidates "${SUYU_LOCAL_EXTERNALS_ROOT}/libusb/libusb")
    endif()
    foreach(_local_candidate IN LISTS _local_candidates)
        # A wrapper directory is not a source checkout (libusb and ffmpeg).
        if(_local_key STREQUAL "ffmpeg")
            set(_local_marker "${_local_candidate}/libavcodec/avcodec.h")
        elseif(_local_key STREQUAL "libusb")
            set(_local_marker "${_local_candidate}/libusb/libusb.h")
        else()
            set(_local_marker "${_local_candidate}/CMakeLists.txt")
        endif()
        if(EXISTS "${_local_marker}")
            set(${_local_name}_CUSTOM_DIR "${_local_candidate}" CACHE PATH "Local source for ${_local_name}" FORCE)
            string(APPEND _local_report "${_local_name}: ${_local_candidate}\n")
            break()
        endif()
    endforeach()
endforeach()
file(WRITE "${CMAKE_BINARY_DIR}/local-dependencies.txt" "${_local_report}")
message(STATUS "Local dependency map: ${CMAKE_BINARY_DIR}/local-dependencies.txt")
# Source packages, not prebuilt platform artifacts. A caller can still override
# these options deliberately in a separate cache; do not silently do so here.
unset(_local_roots)
unset(_local_packages)
unset(_local_candidates)
