// SPDX-FileCopyrightText: Copyright 2026 suyu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later

// Unit tests for src/common/package_policy.cpp, compiled on its own by
// test_package_policy_unit.py. Everything is synthetic: fake "keys" are
// obvious placeholder hex, "games" are a few header bytes.

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <string>
#include <vector>

#include "common/package_policy.h"

#ifdef _WIN32
#include <windows.h>
#endif

namespace fs = std::filesystem;
using namespace Common::PackagePolicy;

static int g_failures = 0;
static int g_checks = 0;
static std::vector<std::string> g_skips;

#define CHECK(cond)                                                                                \
    do {                                                                                           \
        ++g_checks;                                                                                \
        if (!(cond)) {                                                                             \
            ++g_failures;                                                                          \
            std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);                   \
        }                                                                                          \
    } while (0)

namespace {

const std::string kFakeKey = "00112233445566778899aabbccddeeff";

void Write(const fs::path& path, const std::string& bytes) {
    fs::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
}

std::string Read(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

std::string Nso() {
    std::string bytes(0x200, '\0');
    bytes.replace(0, 4, "NSO0");
    return bytes;
}

std::string Npdm() {
    std::string bytes(0x80, '\0');
    bytes.replace(0, 4, "META");
    return bytes;
}

std::string RomFs() {
    std::string bytes(0x200, '\0');
    bytes[0] = 0x50;
    return bytes;
}

std::string KeyText() {
    return "; synthetic placeholder, not a real key\nmaster_key_00 = " + kFakeKey + kFakeKey +
           "\nheader_key = " + kFakeKey + kFakeKey + "\n";
}

bool HasRule(const std::vector<Finding>& findings, const std::string& path,
             const std::string& rule) {
    for (const auto& finding : findings) {
        if (finding.path == path && finding.rule == rule) {
            return true;
        }
    }
    return false;
}

std::map<std::string, std::string> Snapshot(const fs::path& root) {
    std::map<std::string, std::string> files;
    for (const auto& entry : fs::recursive_directory_iterator(root)) {
        if (entry.is_regular_file()) {
            files[fs::relative(entry.path(), root).generic_string()] = Read(entry.path());
        }
    }
    return files;
}

/// A directory link: a symlink where allowed, else an NTFS junction.
bool MakeDirectoryLink(const fs::path& link, const fs::path& target) {
    std::error_code ec;
    fs::create_directory_symlink(target, link, ec);
    if (!ec) {
        return true;
    }
#ifdef _WIN32
    const std::wstring command = L"cmd /c mklink /J \"" + link.wstring() + L"\" \"" +
                                 target.wstring() + L"\" >nul 2>nul";
    return _wsystem(command.c_str()) == 0 && fs::exists(link);
#else
    return false;
#endif
}

bool MakeFileLink(const fs::path& link, const fs::path& target) {
    std::error_code ec;
    fs::create_symlink(target, link, ec);
    return !ec;
}

void TestNames() {
    for (const char* name : {"prod.keys", "PROD.KEYS", "prod.keys. ", "title.keys_autogenerated",
                             "console.keys_autogenerated", "prod.keys.txt", "prod_keys.txt",
                             ".prod.keys", "anything.keys", "keys.txt", "dev.keys",
                             "0100000000f02001000000000000000a.tik", "Ticket.TIK. "}) {
        CHECK(IsKeyFileName(name));
    }
    for (const char* name : {"main", "keys", "prodkeys.png", "README.md", "romfs.bin",
                             "ticket.txt", "tik"}) {
        CHECK(!IsKeyFileName(name));
    }
    for (const char* name : {"BOOT0", "boot1.bin", "PRODINFO", "rawnand.bin.00", "SYSTEM.bin",
                             "BCPKG2-1-Normal-Main", "package2"}) {
        CHECK(IsFirmwareOrNandName(name));
    }
    CHECK(!IsFirmwareOrNandName("main"));
    CHECK(IsFirmwarePath("nand/system/contents/registered/x.nca"));
    CHECK(IsFirmwarePath("user/nand/system/save/8000000000000043/0"));
    CHECK(!IsFirmwarePath("user/nand/user/save/0000000000000000"));
    // The installed-ticket store, even outside a folder named nand.
    CHECK(IsFirmwarePath("nand/system/tickets/x"));
    CHECK(IsFirmwarePath("data/system/tickets"));
    CHECK(!IsFirmwarePath("system/ticketsheet.txt"));
    CHECK(NormalizeName("Prod.Keys. . ") == "prod.keys");
    CHECK(IsOsMetadataName("Thumbs.db") && IsOsMetadataName(".DS_Store"));
}

void TestKeyText() {
    CHECK(ContainsKeyText(KeyText()));
    CHECK(ContainsKeyText("titlekek_0a=" + kFakeKey));
    CHECK(ContainsKeyText("key_area_key_application_1f = " + kFakeKey + "\r\n"));
    // title.keys form: rights ID = title key.
    CHECK(ContainsKeyText(kFakeKey + " = " + kFakeKey + "\n"));
    CHECK(!ContainsKeyText("static const u32 table = 0x00112233;\nint a = 1;\n"));
    CHECK(!ContainsKeyText("master_key_00 = too_short\n"));
    CHECK(!ContainsKeyText("build_id = " + kFakeKey + kFakeKey + "\n"));
}

void TestSignatures() {
    const std::string nsp = "PFS0" + std::string(60, '\0');
    CHECK(MatchContentSignature(std::span{reinterpret_cast<const std::uint8_t*>(nsp.data()),
                                          nsp.size()})
              .has_value());
    std::string xci(0x200, '\0');
    xci.replace(0x100, 4, "HEAD");
    CHECK(MatchContentSignature(std::span{reinterpret_cast<const std::uint8_t*>(xci.data()),
                                          xci.size()})
              .has_value());
    const std::string text = "hello world";
    CHECK(!MatchContentSignature(std::span{reinterpret_cast<const std::uint8_t*>(text.data()),
                                           text.size()})
               .has_value());
}

void TestPaths(const fs::path& root) {
    CHECK(IsWithin(root, root / "a" / "b"));
    CHECK(IsWithin(root, root));
    CHECK(!IsWithin(root / "a", root / "a" / ".." / "b"));
    // A string prefix is not containment.
    CHECK(!IsWithin(root / "pkg", root / "pkg-other" / "x"));
#ifdef _WIN32
    CHECK(IsWithin(root / "Pkg", root / "pKG" / "user"));
#endif
    CHECK(Overlaps(root / "a", root / "a" / "b") && Overlaps(root / "a" / "b", root / "a"));
    CHECK(!Overlaps(root / "a", root / "b"));
    CHECK(!AcceptInstalledRoot(root / "pkg", root / "pkg" / "user").has_value());
    CHECK(!AcceptInstalledRoot(root / "pkg", root / "pkg").has_value());
    CHECK(AcceptInstalledRoot(root / "pkg", root / "installed" / "user").has_value());
}

void TestExeFsPlan(const fs::path& root) {
    const fs::path exefs = root / "exefs-valid";
    Write(exefs / "main", Nso());
    Write(exefs / "rtld", Nso());
    Write(exefs / "subsdk0", Nso());
    Write(exefs / "main.npdm", Npdm());
    Write(exefs / "romfs.bin", RomFs());
    Write(exefs / "desktop.ini", "[.ShellClassInfo]\n");
    fs::create_directories(exefs / "romfs");
    ExeFsPlan plan = PlanExtractedExeFs(exefs);
    CHECK(plan.Ok());
    CHECK(plan.files.size() == 5);
    CHECK(plan.ignored.size() == 2);
    CHECK(plan.Find(ExeFsRole::RomFs) != nullptr);

    // Unknown siblings and dummy key sentinels are rejected, not skipped.
    const fs::path dirty = root / "exefs-dirty";
    fs::copy(exefs, dirty, fs::copy_options::recursive);
    Write(dirty / "notes.txt", "unrelated");
    Write(dirty / "prod.keys", KeyText());
    Write(dirty / "Title.Keys_Autogenerated", KeyText());
    Write(dirty / "BOOT0", std::string(64, '\0'));
    Write(dirty / "main.txt", Nso()); // misleading extension
    Write(dirty / "0100000000f02001000000000000000a.tik", "synthetic");
    plan = PlanExtractedExeFs(dirty);
    CHECK(!plan.Ok());
    CHECK(HasRule(plan.rejected, "notes.txt", "unexpected-file"));
    CHECK(HasRule(plan.rejected, "prod.keys", "key-file"));
    CHECK(HasRule(plan.rejected, "Title.Keys_Autogenerated", "key-file"));
    CHECK(HasRule(plan.rejected, "0100000000f02001000000000000000a.tik", "key-file"));
    CHECK(HasRule(plan.rejected, "BOOT0", "firmware"));
    CHECK(HasRule(plan.rejected, "main.txt", "unexpected-file"));

    // A module name holding something else fails format validation.
    const fs::path forged = root / "exefs-forged";
    Write(forged / "main", Nso());
    Write(forged / "sdk", KeyText());
    Write(forged / "main.npdm", "PFS0" + std::string(60, '\0'));
    plan = PlanExtractedExeFs(forged);
    CHECK(HasRule(plan.rejected, "sdk", "invalid-format"));
    CHECK(HasRule(plan.rejected, "main.npdm", "invalid-format"));

    const fs::path no_main = root / "exefs-no-main";
    Write(no_main / "rtld", Nso());
    CHECK(!PlanExtractedExeFs(no_main).Ok());
}

void TestLinks(const fs::path& root) {
    const fs::path outside = root / "outside";
    Write(outside / "prod.keys", KeyText());
    Write(outside / "main", Nso());
    const fs::path exefs = root / "exefs-link";
    Write(exefs / "main", Nso());
    if (MakeDirectoryLink(exefs / "escape", outside)) {
        const ExeFsPlan plan = PlanExtractedExeFs(exefs);
        CHECK(HasRule(plan.rejected, "escape", "link"));
        // A path through a linked folder resolves outside the source root.
        std::string error;
        CHECK(!CopyFileNoFollow(exefs, exefs / "escape" / "main", root / "copied-main", &error));
        CHECK(!fs::exists(root / "copied-main"));
        // Copying a tree that holds a junction fails without following it.
        const fs::path tree = root / "tree-link";
        Write(tree / "save.bin", "save");
        MakeDirectoryLink(tree / "evil", outside);
        CHECK(!CopyTreeNoFollow(tree, root / "tree-copy", &error));
        // Removing a tree deletes the link, never the target.
        CHECK(RemoveTreeNoFollow(tree, &error));
        CHECK(fs::exists(outside / "prod.keys"));
    } else {
        g_skips.push_back("directory link escape (no symlink or junction permission)");
    }
    if (MakeFileLink(exefs / "sdk", outside / "main")) {
        CHECK(HasRule(PlanExtractedExeFs(exefs).rejected, "sdk", "link"));
    } else {
        g_skips.push_back("file symlink escape (symlink creation not permitted)");
    }
    std::string error;
    Write(root / "overlap" / "a.bin", "x");
    CHECK(!CopyTreeNoFollow(root / "overlap", root / "overlap" / "inner", &error));
}

void TestCopy(const fs::path& root) {
    const fs::path source = root / "copy-src";
    Write(source / "a" / "b.bin", "hello");
    std::string error;
    CHECK(CopyFileNoFollow(source, source / "a" / "b.bin", root / "copy-dst.bin", &error));
    CHECK(Read(root / "copy-dst.bin") == "hello");
    // Never over an existing file.
    CHECK(!CopyFileNoFollow(source, source / "a" / "b.bin", root / "copy-dst.bin", &error));
    // Outside the declared root.
    CHECK(!CopyFileNoFollow(source / "a" / "nothing", source / "a" / "b.bin", root / "x.bin",
                            &error));
    CHECK(CopyTreeNoFollow(source, root / "copy-tree", &error));
    CHECK(Read(root / "copy-tree" / "a" / "b.bin") == "hello");
    CHECK(!CopyTreeNoFollow(source, root / "copy-tree", &error)); // exists
    Write(source / "a" / "prod.keys", KeyText());
    CHECK(!CopyTreeNoFollow(source, root / "copy-tree-2", &error));
    fs::remove(source / "a" / "prod.keys");
    Write(source / "a" / "renamed.dat", KeyText());
    CHECK(!CopyTreeNoFollow(source, root / "copy-tree-3", &error));
}

fs::path MakePackage(const Staging& staging, const std::string& title) {
    const fs::path pkg = staging.root;
    Write(pkg / "Game.exe", "MZ launcher");
    Write(pkg / "launch.bat", "@echo off\n");
    Write(pkg / "README_NATIVE_EXPORT.txt", "readme\n");
    Write(pkg / "export-package.json",
          "{\"schema\": \"" + std::string{kExportManifestSchema} + "\"}\n");
    Write(pkg / "avcodec-61.dll", "MZ dll");
    Write(pkg / "user" / "config" / "game-source.ini", "path=%USERPROFILE%\\Games\\game.nsp\n");
    Write(pkg / "LICENSES" / "LICENSE.txt", "GPL\n");
    fs::create_directories(pkg / "mods");
    Write(pkg / "user" / "config" / "sdl2-config.ini", "[Renderer]\nbackend=1\n");
    Write(pkg / "user" / "nand" / "user" / "save" / "0000000000000000" /
              "00112233445566778899aabbccddeeff" / title / "0" / "save.bin",
          "save");
    return pkg;
}

LocalExportExpectation Expect(const std::string& title) {
    LocalExportExpectation expect;
    expect.platform = Platform::Windows;
    expect.package_name = "Game";
    expect.title_id_hex = title;
    expect.runtime_dlls = {"avcodec-61.dll"};
    return expect;
}

void TestValidation(const fs::path& root) {
    const std::string title = "0100000000010000";
    std::string error;
    auto staging = CreateStaging(root / "out-validate", &error);
    CHECK(staging.has_value());
    const fs::path pkg = MakePackage(*staging, title);
    CHECK(ValidateLocalExport(pkg, Expect(title)).empty());

    Write(pkg / "user" / "keys" / "prod.keys", KeyText());
    // No game data of any kind: not the ExeFS, not the RomFS, not a container.
    Write(pkg / "exefs" / "main", Nso());
    Write(pkg / "exefs" / "romfs.bin", RomFs());
    Write(pkg / "stray.txt", "x");
    Write(pkg / "user" / "nand" / "user" / "save" / "0000000000000000" /
              "00112233445566778899aabbccddeeff" / "0100000000020000" / "other.bin",
          "other title");
    Write(pkg / "user" / "nand" / "system" / "Contents" / "registered" / "fw.nca", "fw");
    Write(pkg / "mods" / "leftover.txt", "x");
    Write(pkg / "user" / "cache" / "shader" / "0100000000020000" / "vulkan.bin", "x");
    const auto findings = ValidateLocalExport(pkg, Expect(title));
    CHECK(HasRule(findings, "user/keys", "unexpected"));
    CHECK(HasRule(findings, "exefs", "unexpected"));
    CHECK(HasRule(findings, "stray.txt", "unexpected"));
    CHECK(HasRule(findings, "user/nand/system", "unexpected"));
    CHECK(HasRule(findings, "mods/leftover.txt", "unexpected"));
    CHECK(HasRule(findings, "user/cache/shader/0100000000020000", "unexpected"));
    bool other_title = false;
    for (const auto& finding : findings) {
        other_title |= finding.path.find("0100000000020000") != std::string::npos;
    }
    CHECK(other_title);

    // Source exports keep aot_cache; a stray container or key text in it is caught.
    auto source = CreateStaging(root / "out-validate-src", &error);
    const fs::path src_pkg = MakePackage(*source, title);
    auto expect = Expect(title);
    expect.allow_aot_cache = true;
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "src" / "unit0.c", "int x = 1;\n");
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "CMakeLists.txt", "project(x C)\n");
    CHECK(ValidateLocalExport(src_pkg, expect).empty());
    // The game's own modules, bundled segments, a standalone runner or guest dumps
    // never travel with the generated project.
    Write(src_pkg / "aot_cache" / "exefs" / "nso" / "main", Nso());
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "data" / "text.bin", "code");
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "main.c", "int main(void){}\n");
    Write(src_pkg / "aot_cache" / "debug" / "code" / "main" / "b.guest.bin", "code");
    {
        const auto game_data = ValidateLocalExport(src_pkg, expect);
        CHECK(HasRule(game_data, "aot_cache/exefs/nso", "unexpected"));
        CHECK(HasRule(game_data, "aot_cache/exefs/main/data", "unexpected"));
        CHECK(HasRule(game_data, "aot_cache/exefs/main/main.c", "unexpected"));
        CHECK(HasRule(game_data, "aot_cache/debug", "unexpected"));
    }
    fs::remove_all(src_pkg / "aot_cache" / "exefs" / "nso");
    fs::remove_all(src_pkg / "aot_cache" / "exefs" / "main" / "data");
    fs::remove(src_pkg / "aot_cache" / "exefs" / "main" / "main.c");
    fs::remove_all(src_pkg / "aot_cache" / "debug");
    CHECK(ValidateLocalExport(src_pkg, expect).empty());
    Write(src_pkg / "aot_cache" / "game.nsp", "PFS0" + std::string(60, '\0'));
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "src" / "keys.h", KeyText());
    Write(src_pkg / "aot_cache" / "blob.bin", "PFS0" + std::string(60, '\0'));
    Write(src_pkg / "aot_cache" / "exefs" / "main" / "src" / "title.tik", "synthetic");
    const auto src_findings = ValidateLocalExport(src_pkg, expect);
    CHECK(HasRule(src_findings, "aot_cache/game.nsp", "game-container"));
    CHECK(HasRule(src_findings, "aot_cache/exefs/main/src/keys.h", "key-text"));
    CHECK(HasRule(src_findings, "aot_cache/exefs/main/src/title.tik", "key-file"));
    CHECK(HasRule(src_findings, "aot_cache/blob.bin", "signature"));
    // Without allow_aot_cache the whole folder is unexpected.
    CHECK(HasRule(ValidateLocalExport(src_pkg, Expect(title)), "aot_cache", "unexpected"));
    CHECK(RemoveStaging(*staging, &error));
    CHECK(RemoveStaging(*source, &error));
}

void TestPortable(const fs::path& root) {
    const std::string title = "0100000000010000";
    std::string error;
    auto staging = CreateStaging(root / "out-portable", &error);
    CHECK(staging.has_value());
    const fs::path pkg = MakePackage(*staging, title);
    const std::string sealed(0x1000, 'Z');
    Write(pkg / "game" / "base.sealed", sealed);
    Write(pkg / "game" / "update-0.sealed", sealed);
    Write(pkg / "game" / "dlc-0.sealed", sealed);
    Write(pkg / "game" / "dlc-1.sealed", sealed);
    Write(pkg / "game" / "seal.json", "{\"format\": \"suyu-portable-seal-1\"}\n");

    // Without a portable expectation and manifest, sealed files are not part of an export.
    {
        const auto findings = ValidateLocalExport(pkg, Expect(title));
        CHECK(HasRule(findings, "game", "unexpected"));
    }
    auto expect = Expect(title);
    expect.portable = true;
    // The exporter's choice alone is not enough: the manifest must declare it too.
    CHECK(HasRule(ValidateLocalExport(pkg, expect), "export-package.json", "package-type"));
    Write(pkg / "export-package.json", "{\"schema\": \"" + std::string{kExportManifestSchema} +
                                           "\",\n  \"package_type\": \"portable\"}\n");
    CHECK(ManifestDeclaresPortable(Read(pkg / "export-package.json")));
    CHECK(!ManifestDeclaresPortable("{\"package_type\": \"reference\"}"));
    CHECK(ValidateLocalExport(pkg, expect).empty());
    // A manifest that declares a portable export is wrong for any other export.
    CHECK(HasRule(ValidateLocalExport(pkg, Expect(title)), "export-package.json", "package-type"));

    // A container that is not sealed is still refused, whatever its name.
    Write(pkg / "game" / "update-1.sealed", "PFS0" + std::string(60, '\0'));
    Write(pkg / "game" / "dlc-2.sealed", "PFS0" + std::string(60, '\0'));
    Write(pkg / "game" / "dlc-3.sealed", KeyText());
    Write(pkg / "game" / "dlc-x.sealed", sealed);
    Write(pkg / "game" / "dlc-12345.sealed", sealed);
    Write(pkg / "game" / "game.nsp", "x");
    Write(pkg / "game" / "notes.txt", "x");
    Write(pkg / "game" / "prod.keys", KeyText());
    Write(pkg / "game" / "update-2.sealed", KeyText());
    {
        const auto findings = ValidateLocalExport(pkg, expect);
        CHECK(HasRule(findings, "game/update-1.sealed", "signature"));
        CHECK(HasRule(findings, "game/game.nsp", "unexpected"));
        CHECK(HasRule(findings, "game/notes.txt", "unexpected"));
        CHECK(HasRule(findings, "game/prod.keys", "unexpected"));
        CHECK(HasRule(findings, "game/update-2.sealed", "key-text"));
        CHECK(HasRule(findings, "game/dlc-2.sealed", "signature"));
        CHECK(HasRule(findings, "game/dlc-3.sealed", "key-text"));
        CHECK(HasRule(findings, "game/dlc-x.sealed", "unexpected"));
        CHECK(HasRule(findings, "game/dlc-12345.sealed", "unexpected"));
    }
    for (const char* name : {"update-1.sealed", "game.nsp", "notes.txt", "prod.keys",
                             "update-2.sealed", "dlc-2.sealed", "dlc-3.sealed", "dlc-x.sealed",
                             "dlc-12345.sealed"}) {
        fs::remove(pkg / "game" / name);
    }
    // Keys are refused anywhere else in a portable export too.
    Write(pkg / "prod.keys", KeyText());
    CHECK(HasRule(ValidateLocalExport(pkg, expect), "prod.keys", "unexpected"));
    fs::remove(pkg / "prod.keys");
    CHECK(ValidateLocalExport(pkg, expect).empty());

    // Sealed folders only sit at the top of a Windows package, and need both files.
    fs::remove(pkg / "game" / "seal.json");
    CHECK(HasRule(ValidateLocalExport(pkg, expect), "game", "portable-incomplete"));
    CHECK(RemoveStaging(*staging, &error));

    // DLC title IDs: the game's base title, the add-on offset, an index from 1 to 0x7FF.
    CHECK(IsAddOnContentOf(0x0100000000011001, 0x0100000000010000));
    CHECK(IsAddOnContentOf(0x01000000000117FF, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000011000, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000011800, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000010800, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000010000, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000033001, 0x0100000000010000));
    CHECK(!IsAddOnContentOf(0x0100000000011001, 0));
}

void TestPromotion(const fs::path& root) {
    const std::string title = "0100000000010000";
    const fs::path out = root / "out-promote";
    const fs::path dest = out / "Game";
    std::string error;

    // A dirty earlier package: keys, firmware markers, old optional data.
    Write(dest / "README_NATIVE_EXPORT.txt", "old\n");
    Write(dest / "export-package.json",
          "{\"schema\": \"" + std::string{kExportManifestSchema} + "\"}\n");
    Write(dest / "prod.keys", KeyText());
    Write(dest / "user" / "nand" / "system" / "Contents" / "registered" / "BOOT0", "fw");
    Write(dest / "user" / "nand" / "user" / "save" / "0000000000000000" /
              "00112233445566778899aabbccddeeff" / title / "old-save.bin",
          "precious save");
    Write(dest / "user" / "config" / "custom" / "0100000000010000.ini", "[System]\n");
    const auto before = Snapshot(dest);
    CHECK(ClassifyDestination(dest) == Existing::ExporterManaged);

    // Fail policy: structured conflict, nothing touched.
    auto staging = CreateStaging(out, &error);
    const fs::path pkg = MakePackage(*staging, title);
    fs::remove_all(pkg / "user" / "nand"); // this export deselects saves
    auto result = Promote(*staging, dest, ConflictPolicy::Fail);
    CHECK(!result.ok && result.conflict);
    CHECK(Snapshot(dest) == before);
    // Cancelling here: only this run's staging goes, the old package stays.
    CHECK(RemoveStaging(*staging, &error));
    CHECK(!fs::exists(staging->root) && !fs::exists(staging->work));
    CHECK(Snapshot(dest) == before);

    // Replace: the old package is kept whole as a backup, the new one holds
    // only what this export produced.
    staging = CreateStaging(out, &error);
    MakePackage(*staging, title);
    fs::remove_all(staging->root / "user" / "nand");
    result = Promote(*staging, dest, ConflictPolicy::ReplaceWithBackup);
    CHECK(result.ok);
    CHECK(!result.backup_path.empty() && Snapshot(result.backup_path) == before);
    CHECK(!fs::exists(dest / "prod.keys"));
    CHECK(!fs::exists(dest / "user" / "nand"));
    CHECK(!fs::exists(dest / "user" / "config" / "custom"));
    CHECK(ValidateLocalExport(dest, Expect(title)).empty());
    CHECK(RemoveStaging(*staging, &error)); // marker and work folder only
    CHECK(fs::exists(dest / "Game.exe"));

    // KeepBoth picks a fresh name.
    staging = CreateStaging(out, &error);
    MakePackage(*staging, title);
    result = Promote(*staging, dest, ConflictPolicy::KeepBoth);
    CHECK(result.ok && result.final_path.filename() == fs::path{"Game (2)"});
    RemoveStaging(*staging, &error);

    // A foreign folder is never replaced.
    const fs::path foreign = out / "Photos";
    Write(foreign / "holiday.jpg", "jpg");
    staging = CreateStaging(out, &error);
    MakePackage(*staging, title);
    result = Promote(*staging, foreign, ConflictPolicy::ReplaceWithBackup);
    CHECK(!result.ok && result.conflict);
    CHECK(Read(foreign / "holiday.jpg") == "jpg");
    CHECK(RemoveStaging(*staging, &error));

    // A failed move restores the previous package.
    staging = CreateStaging(out, &error);
    const auto current = Snapshot(dest);
    fs::remove_all(staging->root); // nothing left to move in
    result = Promote(*staging, dest, ConflictPolicy::ReplaceWithBackup);
    CHECK(!result.ok);
    CHECK(Snapshot(dest) == current);
    CHECK(RemoveStaging(*staging, &error));

    // Staging owned by someone else is never removed.
    Staging stranger{out, out / ".suyu-export-deadbeef", out / ".suyu-export-deadbeef.work",
                     "deadbeef"};
    Write(stranger.root / "keep.txt", "not ours");
    CHECK(!RemoveStaging(stranger, &error));
    CHECK(fs::exists(stranger.root / "keep.txt"));
    // A destination outside the output folder is refused.
    staging = CreateStaging(out, &error);
    result = Promote(*staging, root / "elsewhere" / "Game", ConflictPolicy::Fail);
    CHECK(!result.ok);
    RemoveStaging(*staging, &error);
}

void TestSettings() {
    CHECK(IsExportableSettingKey("Renderer/backend"));
    CHECK(IsExportableSettingKey("Renderer/backend/default"));
    CHECK(IsExportableSettingKey("System/language_index"));
    for (const char* key :
         {"System/device_name", "System/current_user", "System/rng_seed", "System/custom_rtc",
          "System/program_args", "Renderer/vulkan_device", "Audio/output_device",
          "Audio/input_device", "Audio/dump_audio_commands", "Cpu/cpu_debug_mode",
          "Renderer/renderer_debug", "WebService/suyu_token", "WebService/suyu_username",
          "Data%20Storage/nand_directory", "UI/Paths\\gamedirs\\1\\path", "Renderer/evil",
          "System/application_version_override", "Renderer/backend/use_global"}) {
        CHECK(!IsExportableSettingKey(key));
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: policy_unit <scratch dir>\n");
        return 2;
    }
    const fs::path root = fs::absolute(argv[1]);
    fs::remove_all(root);
    fs::create_directories(root);
    TestNames();
    TestKeyText();
    TestSignatures();
    TestPaths(root);
    TestExeFsPlan(root);
    TestLinks(root);
    TestCopy(root);
    TestValidation(root);
    TestPortable(root);
    TestPromotion(root);
    TestSettings();
    for (const auto& skip : g_skips) {
        std::printf("SKIP %s\n", skip.c_str());
    }
    std::printf("%d checks, %d failures, %zu skipped\n", g_checks, g_failures, g_skips.size());
    return g_failures == 0 ? 0 : 1;
}
