"""suyu reads the keys the user installs and never makes new ones.

The notice says suyu will not generate, ship or download Nintendo keys. The
core used to derive keys from console data (BOOT0, fuses, package2), pull the
SD seed out of NAND saves, and write everything it derived to
*.keys_autogenerated files. This guards against that coming back.
"""
from pathlib import Path
import re
import unittest

ROOT = Path(__file__).resolve().parents[2]


def source(path):
    return (ROOT / path).read_text(encoding='utf-8')


class NoKeyGeneration(unittest.TestCase):
    def test_no_derivation_from_console_data(self):
        keys = source('src/core/crypto/key_manager.cpp') + source('src/core/crypto/key_manager.h')
        for name in ('DeriveBase', 'PopulateFromPartitionData', 'DeriveKeyblobKey',
                     'DeriveMasterKey', 'DecryptKeyblob', 'DeriveGeneralPurposeKeys',
                     'DeriveETicket', 'DeriveSDSeed'):
            self.assertIsNone(re.search(r'\b' + name + r'\b', keys), name)
        pdm = source('src/core/crypto/partition_data_manager.cpp')
        for name in ('GetSecureBootKey', 'GetEncryptedKeyblob', 'DecryptPackage2',
                     'GetETicketExtendedKek'):
            self.assertNotIn(name, pdm)
        self.assertNotIn('PopulateFromPartitionData', source('src/core/file_sys/bis_factory.cpp'))
        self.assertNotIn('DeriveSDSeedLazy', source('src/core/file_sys/xts_archive.cpp'))

    def test_no_key_files_written(self):
        for path in (ROOT / 'src').rglob('*.cpp'):
            text = path.read_text(encoding='utf-8', errors='replace')
            with self.subTest(path=path.relative_to(ROOT).as_posix()):
                self.assertNotIn('WriteKeyToFile', text)
                # Reading existing *_autogenerated files a user already has is fine;
                # opening one for writing is not.
                self.assertIsNone(re.search(
                    r'keys_autogenerated"[^;\n]*FileAccessMode::(Write|Append|ReadWrite)', text))


if __name__ == '__main__':
    unittest.main()
