// Writes the C the differential driver links: every word of words.h translated
// by the current emitter into ops_soft.c (the default, ABI 5 text) and
// ops_fpx.c (FPX1), each with its runtime header; the two negative controls
// ops_nokeep.c and ops_nomid.c; and hw.c, which runs the same words on an
// AArch64 host.
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include "core/recompiler/arm64_to_c.h"

extern "C" {
#include "words.h"
}

namespace {

bool Write(const std::filesystem::path& path, const std::string& text) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary);
    out.write(text.data(), static_cast<std::streamsize>(text.size()));
    return static_cast<bool>(out);
}

// The runtime C includes "recomp_runtime.h"; point it at the header written here.
std::string Renamed(std::string text, const std::string& header) {
    const std::string from = "#include \"recomp_runtime.h\"";
    for (size_t at = text.find(from); at != std::string::npos; at = text.find(from, at))
        text.replace(at, from.size(), "#include \"" + header + "\"");
    return text;
}

// Replaces the one occurrence of `from` in `text`; false if it is missing.
bool Replace(std::string& text, const std::string& from, const std::string& to) {
    const size_t at = text.find(from);
    if (at == std::string::npos || text.find(from, at + 1) != std::string::npos) {
        std::fprintf(stderr, "control edit not found: %s\n", from.c_str());
        return false;
    }
    text.replace(at, from.size(), to);
    return true;
}

// One translation unit of op functions plus its table, named g_ops_<tag>.
bool Ops(const std::filesystem::path& dir, const std::string& tag, const std::string& header) {
    std::string out = "/* Generated by fpx_gen. */\n#include \"" + header +
                      "\"\n#include <string.h>\n#include <math.h>\n";
    std::string table = "typedef void (*FpxOpFn)(GuestContext*);\nconst FpxOpFn g_ops_" + tag + "[]={";
    for (unsigned i = 0; i < FPX_NWORDS; ++i) {
        std::string code;
        bool unhandled = false;
        suyu::recomp::Translate(g_fpx_words[i].word, 0x100, code, &unhandled);
        if (unhandled) {
            std::fprintf(stderr, "unhandled %08x %s\n", g_fpx_words[i].word, g_fpx_words[i].text);
            return false;
        }
        out += "static void op" + std::to_string(i) + "(GuestContext*c){\n" + code + "}\n";
        table += "op" + std::to_string(i) + ",";
    }
    return Write(dir / ("ops_" + tag + ".c"), out + table + "};\n");
}

// Native execution: q0-q3, x0, x1 and NZCV from `in`, FPCR from the argument,
// FPSR cleared; q0, x0 and NZCV to `out`, FPSR returned.
std::string Hw() {
    std::string out = "/* Generated by fpx_gen. AArch64 hosts only. */\n#include <stdint.h>\n";
    std::string table = "typedef uint64_t (*FpxHwFn)(const uint64_t*,uint64_t*,uint64_t);\n"
                        "const FpxHwFn g_hw[]={";
    for (unsigned i = 0; i < FPX_NWORDS; ++i) {
        char word[16];
        std::snprintf(word, sizeof word, "0x%08x", g_fpx_words[i].word);
        out += "static uint64_t hw" + std::to_string(i) +
               "(const uint64_t* in,uint64_t* out,uint64_t fpcr){ uint64_t fs;\n"
               " __asm__ volatile(\"ldr q0,[%1]\\n ldr q1,[%1,#16]\\n ldr q2,[%1,#32]\\n"
               " ldr q3,[%1,#48]\\n ldr x0,[%1,#64]\\n ldr x1,[%1,#72]\\n ldr x9,[%1,#80]\\n"
               " msr nzcv,x9\\n msr fpcr,%3\\n msr fpsr,xzr\\n .inst " +
               std::string(word) +
               "\\n mrs %0,fpsr\\n msr fpcr,xzr\\n str q0,[%2]\\n str x0,[%2,#16]\\n"
               " mrs x9,nzcv\\n str x9,[%2,#24]\\n\""
               " : \"=&r\"(fs) : \"r\"(in),\"r\"(out),\"r\"(fpcr)"
               " : \"v0\",\"v1\",\"v2\",\"v3\",\"x0\",\"x1\",\"x9\",\"cc\",\"memory\"); return fs; }\n";
        table += "hw" + std::to_string(i) + ",";
    }
    return out + table + "};\n";
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        return 2;
    }
    const std::filesystem::path dir = argv[1];
    suyu::recomp::g_translate_all = true;
    // The runtime C only for recomp_fp_estimate, which a few estimate forms call.
    if (!Write(dir / "rt_soft.h", suyu::recomp::RuntimeH()) ||
        !Write(dir / "rt_soft.c", Renamed(suyu::recomp::RuntimeC(), "rt_soft.h")) ||
        !Ops(dir, "soft", "rt_soft.h") ||
        !Write(dir / "hw.c", Hw())) {
        return 1;
    }
    // FPX1, and the two negative controls: the same text with the keep test
    // reduced to "always" (the D-style build), and without the midpoint test.
    suyu::recomp::g_emit_fpx = true;
    const std::string fpx = suyu::recomp::RuntimeH();
    std::string nokeep = fpx, nomid = fpx;
    const bool edited =
        Replace(nokeep, "#define RECOMP_FPX_BIG32(t) ", "#define RECOMP_FPX_BIG32(t) (1) || ") &&
        Replace(nokeep, "#define RECOMP_FPX_FIN32(t) ", "#define RECOMP_FPX_FIN32(t) (1) || ") &&
        Replace(nokeep, "#define RECOMP_FPX_BIG64(t) ", "#define RECOMP_FPX_BIG64(t) (1) || ") &&
        Replace(nokeep, "#define RECOMP_FPX_FIN64(t) ", "#define RECOMP_FPX_FIN64(t) (1) || ") &&
        Replace(nomid, "#define RECOMP_FPX_MIDPOINT(s) ", "#define RECOMP_FPX_MIDPOINT(s) (0) && ");
    // Only the fpx ops count their fast-path hits.
    const std::string probe = "extern unsigned long long g_fpx_probe[3];\n"
                              "#define RECOMP_FPX_PROBE(k) (++g_fpx_probe[k])\n";
    if (!edited || !Write(dir / "rt_fpx.h", probe + fpx) || !Write(dir / "rt_nokeep.h", nokeep) ||
        !Write(dir / "rt_nomid.h", nomid) || !Ops(dir, "fpx", "rt_fpx.h") ||
        !Ops(dir, "nokeep", "rt_nokeep.h") || !Ops(dir, "nomid", "rt_nomid.h")) {
        return 1;
    }
    // The shadow instrumentation build: exact results always, with the fast
    // path compared behind them (recomp_fpx_shadow, from the runtime C).
    suyu::recomp::g_emit_fpx_shadow = true;
    if (!Write(dir / "rt_shadow.h", suyu::recomp::RuntimeH()) ||
        !Write(dir / "shadow_rt.c",
               "#include \"rt_shadow.h\"\n#include <stdlib.h>\n" +
                   std::string(suyu::recomp::FpxShadowC())) ||
        !Ops(dir, "shadow", "rt_shadow.h")) {
        return 1;
    }
    return 0;
}
