#!/usr/bin/env python3
"""Regenerate words.h from ops.txt. Needs clang with an AArch64 target and llvm-objdump
(or an AArch64 host's cc and objdump); only required after editing ops.txt."""
import argparse
from pathlib import Path
import re
import subprocess
import tempfile

KINDS = {"S": "'S'", "D": "'D'", "W": "'W'", "X": "'X'", "VS": "'s'", "VD": "'d'"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default="clang")
    parser.add_argument("--objdump", default="llvm-objdump")
    args = parser.parse_args()
    here = Path(__file__).resolve().parent
    rows = []
    for line in (here / "ops.txt").read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        text, kind, arity = (field.strip() for field in line.split("|"))
        rows.append((text, KINDS[kind], int(arity)))
    with tempfile.TemporaryDirectory() as tmp:
        source, obj = Path(tmp) / "ops.s", Path(tmp) / "ops.o"
        source.write_text("".join(text + "\n" for text, _, _ in rows))
        subprocess.run([args.cc, "--target=aarch64-linux-gnu", "-c", source, "-o", obj], check=True)
        dump = subprocess.run([args.objdump, "-d", obj], check=True, capture_output=True,
                              text=True).stdout
    words = re.findall(r"^\s*[0-9a-f]+:\s+([0-9a-f]{8})\s", dump, re.M)
    if len(words) != len(rows):
        raise SystemExit(f"assembled {len(words)} words for {len(rows)} lines")
    out = ["/* Generated by mkwords.py from ops.txt. Do not edit. */\n",
           "typedef struct { uint32_t word; const char* text; char kind; unsigned char arity; } FpxWord;\n",
           "static const FpxWord g_fpx_words[] = {\n"]
    for word, (text, kind, arity) in zip(words, rows):
        out.append(f"    {{0x{word}u, \"{text}\", {kind}, {arity}}},\n")
    out.append("};\n#define FPX_NWORDS (sizeof g_fpx_words / sizeof g_fpx_words[0])\n")
    (here / "words.h").write_text("".join(out), newline="\n")


if __name__ == "__main__":
    main()
