// SPDX-FileCopyrightText: Copyright 2026 suyu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later

#include "common/package_policy.h"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <fstream>
#include <random>
#include <regex>
#include <set>
#include <system_error>
#include <thread>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#else
#include <cerrno>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

namespace Common::PackagePolicy {

namespace fs = std::filesystem;

namespace {

// ---- Tables. tests/package_policy/test_policy_sync.py compares these with
// tools/package_policy/policy.json; change both together. ----

constexpr std::array kKeyFileNamePatterns{
    R"(^(prod|title|console|dev)\.keys(_autogenerated)?([._-].*)?$)",
    R"(^(prod|title|console|dev)[._-]?keys(\.(txt|ini|bak|old|dat))?$)",
    R"(^.*\.keys$)",
    R"(^keys\.(txt|ini|dat)$)",
    R"(^(fuses?|tsec(_keys?)?|secure_boot|sbk)\.(bin|txt|keys)$)",
    // Tickets carry title keys (encrypted, but still key material).
    R"(^.*\.tik$)",
};

constexpr std::array kFirmwareNandNamePatterns{
    R"(^boot[01](\.bin)?$)",
    R"(^rawnand(\.bin)?(\.\d+)?$)",
    R"(^prodinfo(f)?(\.bin)?$)",
    R"(^(safe|system|user)\.bin$)",
    R"(^bcpkg2-[1-4]-.*$)",
    R"(^package[12](\.bin)?$)",
    R"(^(firmware|nand)[._-].*\.(zip|7z|rar|tar)$)",
};

constexpr std::array kFirmwareNandPathPatterns{
    R"((^|/)system/contents/registered(/|$))",
    R"((^|/)nand/system(/|$))",
    R"((^|/)system/save/80000000000000(43|e1|e2|51|52|53)(/|$))",
    // The ticket store suyu keeps for installed NSP content (Core::Crypto::TicketStoreDir).
    R"((^|/)system/tickets(/|$))",
};

constexpr std::array kGameContainerExtensions{".nsp", ".xci", ".nsz", ".xcz", ".nca",
                                              ".ncz", ".nro", ".nso", ".nax0"};

// Key names that carry a two-digit generation suffix ("master_key_0a = ...").
constexpr std::array kIndexedKeyNames{
    "master_key",        "master_kek",       "keyblob",
    "keyblob_key",       "keyblob_mac_key",  "encrypted_keyblob",
    "titlekek",          "package1_key",     "package2_key",
    "key_area_key_application", "key_area_key_ocean", "key_area_key_system",
};

constexpr std::array kPlainKeyNames{
    "header_key",           "header_kek",           "sd_seed",
    "tsec_key",             "secure_boot_key",      "eticket_rsa_kek",
    "eticket_rsa_keypair",  "eticket_extended_kek", "sd_card_kek_source",
    "aes_kek_generation_source", "aes_key_generation_source",
    "bis_key_00",           "bis_key_01",           "bis_key_02",
    "bis_key_03",
};

struct Signature {
    std::string_view name;
    std::size_t offset;
    std::string_view bytes;
};

constexpr std::array kContentSignatures{
    Signature{"Nintendo PFS0 container (NSP)", 0, "PFS0"},
    Signature{"Nintendo HFS0 partition", 0, "HFS0"},
    Signature{"Nintendo XCI header", 256, "HEAD"},
    Signature{"Nintendo NSO executable", 0, "NSO0"},
    Signature{"Nintendo NRO executable", 16, "NRO0"},
    Signature{"Nintendo NPDM metadata", 0, "META"},
    Signature{"Nintendo NAX0 archive", 32, "NAX0"},
    Signature{"Compressed NCZ section table", 16384, "NCZSECTN"},
};

constexpr std::array kModuleNames{"rtld",    "main",    "subsdk0", "subsdk1", "subsdk2",
                                  "subsdk3", "subsdk4", "subsdk5", "subsdk6", "subsdk7",
                                  "subsdk8", "subsdk9", "sdk"};
constexpr std::array kOsMetadataNames{"desktop.ini", "thumbs.db", ".ds_store"};
constexpr std::uint64_t kNacpSize = 0x4000;
constexpr std::uint64_t kRomFsHeaderSize = 0x50;
constexpr std::uint64_t kNsoHeaderSize = 0x100;
constexpr std::uint64_t kNcaHeaderSize = 0xC00;

// Settings a package may carry, by the section QSettings stores them under.
// Left out on purpose: device and account selectors (vulkan_device,
// output_device, input_device, device_name, current_user), program_args,
// the version overrides WritePortableVersionOverride owns, the RNG seed and
// custom RTC (debugging overrides), dump_audio_commands, and every setting in
// the CpuDebug, CpuUnsafe, RendererDebug, Debugging, DataStorage, WebService,
// Network, UI and input categories - even where they share these sections.
constexpr std::string_view kExportableSettings[]{
    "Core/use_multi_core",
    "Core/memory_layout_mode",
    "Core/use_speed_limit",
    "Core/speed_limit",
    "Core/slow_speed_limit",
    "Core/turbo_speed_limit",
    "Core/current_speed_mode",
    "Core/sync_core_speed",
    "Cpu/cpu_backend",
    "Cpu/cpu_accuracy",
    "Cpu/fast_cpu_time",
    "Cpu/use_custom_cpu_ticks",
    "Cpu/cpu_ticks",
    "Renderer/backend",
    "Renderer/resolution_setup",
    "Renderer/use_vsync",
    "Renderer/scaling_filter",
    "Renderer/fsr_sharpening_slider",
    "Renderer/aspect_ratio",
    "Renderer/anti_aliasing",
    "Renderer/use_asynchronous_gpu_emulation",
    "Renderer/fullscreen_mode",
    "Renderer/bg_red",
    "Renderer/bg_green",
    "Renderer/bg_blue",
    "Renderer/optimize_spirv_output",
    "Renderer/gpu_accuracy",
    "Renderer/dma_accuracy",
    "Renderer/gpu_fence_behavior",
    "Renderer/vram_usage_mode",
    "Renderer/nvdec_emulation",
    "Renderer/max_anisotropy",
    "Renderer/accelerate_astc",
    "Renderer/frame_pacing_mode",
    "Renderer/astc_recompression",
    "Renderer/sync_memory_operations",
    "Renderer/force_max_clock",
    "Renderer/use_disk_shader_cache",
    "Renderer/use_vulkan_driver_pipeline_cache",
    "Renderer/enable_compute_pipelines",
    "Renderer/use_video_framerate",
    "Renderer/use_reactive_flushing",
    "Renderer/barrier_feedback_loops",
    "Renderer/enable_buffer_history",
    "Renderer/use_optimized_vertex_buffers",
    "Renderer/enable_gpu_buffer_readback",
    "Renderer/use_fast_gpu_time",
    "Renderer/fast_gpu_time",
    "Renderer/skip_cpu_inner_invalidation",
    "Renderer/async_presentation",
    "Renderer/fix_bloom_effects",
    "Renderer/emulate_bgr565",
    "Renderer/rescale_hack",
    "Renderer/use_asynchronous_shaders",
    "Renderer/gpu_unswizzle_texture_size",
    "Renderer/gpu_unswizzle_stream_size",
    "Renderer/gpu_unswizzle_chunk_size",
    "Renderer/gpu_unswizzle_enabled",
    "Renderer/use_graphics_pipeline_library",
    "Renderer/dyna_state",
    "Renderer/sample_shading_fraction",
    "Renderer/vertex_input_dynamic_state",
    "Audio/output_engine",
    "Audio/volume",
    "Audio/audio_muted",
    "System/language_index",
    "System/region_index",
    "System/time_zone_index",
    "System/use_docked_mode",
    "System/sound_index",
    "LibraryApplet/cabinet_applet_mode",
    "LibraryApplet/controller_applet_mode",
    "LibraryApplet/data_erase_applet_mode",
    "LibraryApplet/error_applet_mode",
    "LibraryApplet/net_connect_applet_mode",
    "LibraryApplet/player_select_applet_mode",
    "LibraryApplet/swkbd_applet_mode",
    "LibraryApplet/mii_edit_applet_mode",
    "LibraryApplet/web_applet_mode",
    "LibraryApplet/shop_applet_mode",
    "LibraryApplet/photo_viewer_applet_mode",
    "LibraryApplet/offline_web_applet_mode",
    "LibraryApplet/login_share_applet_mode",
    "LibraryApplet/wifi_web_auth_applet_mode",
    "LibraryApplet/my_page_applet_mode",
    "LibraryApplet/enable_overlay",
};

// ---- helpers ----

char Lower(char c) {
    return c >= 'A' && c <= 'Z' ? static_cast<char>(c - 'A' + 'a') : c;
}

bool IsHex(char c) {
    return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
}

template <std::size_t N>
bool MatchesAny(const std::array<const char*, N>& patterns, const std::string& text) {
    for (const char* pattern : patterns) {
        // Compiled once per call; names are short and these checks are not hot.
        if (std::regex_search(text, std::regex{pattern, std::regex::ECMAScript})) {
            return true;
        }
    }
    return false;
}

std::string Utf8(const fs::path& path) {
    const auto text = path.generic_u8string();
    return std::string{reinterpret_cast<const char*>(text.data()), text.size()};
}

std::string Relative(const fs::path& root, const fs::path& path) {
    std::error_code ec;
    const auto relative = fs::relative(path, root, ec);
    return Utf8(ec ? path.filename() : relative);
}

std::string ToLower(std::string text) {
    std::transform(text.begin(), text.end(), text.begin(), Lower);
    return text;
}

bool ComponentEquals(const fs::path& a, const fs::path& b) {
#ifdef _WIN32
    const std::wstring& wa = a.native();
    const std::wstring& wb = b.native();
    return CompareStringOrdinal(wa.c_str(), static_cast<int>(wa.size()), wb.c_str(),
                                static_cast<int>(wb.size()), TRUE) == CSTR_EQUAL;
#else
    return a == b;
#endif
}

fs::path Resolve(const fs::path& path) {
    std::error_code ec;
    fs::path absolute = fs::absolute(path, ec);
    if (ec) {
        return path.lexically_normal();
    }
    fs::path resolved = fs::weakly_canonical(absolute, ec);
    return (ec ? absolute : resolved).lexically_normal();
}

std::optional<std::vector<std::uint8_t>> ReadHead(const fs::path& path, std::size_t size) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        return std::nullopt;
    }
    std::vector<std::uint8_t> bytes(size);
    in.read(reinterpret_cast<char*>(bytes.data()), static_cast<std::streamsize>(size));
    bytes.resize(static_cast<std::size_t>(in.gcount()));
    return bytes;
}

std::uint64_t ReadU64(const std::vector<std::uint8_t>& bytes, std::size_t offset) {
    std::uint64_t value = 0;
    for (std::size_t i = 0; i < 8 && offset + i < bytes.size(); ++i) {
        value |= static_cast<std::uint64_t>(bytes[offset + i]) << (8 * i);
    }
    return value;
}

bool StartsWith(const std::vector<std::uint8_t>& bytes, std::string_view magic) {
    return bytes.size() >= magic.size() &&
           std::memcmp(bytes.data(), magic.data(), magic.size()) == 0;
}

/// Name, key-text and signature checks every copied or packaged file gets.
/// `allowed_signature` names the one signature this file's role expects.
std::optional<Finding> CheckFileContent(const fs::path& path, const std::string& relative,
                                        std::string_view allowed_signature = {}) {
    const std::string name = NormalizeName(Utf8(path.filename()));
    if (IsKeyFileName(name)) {
        return Finding{relative, "key-file", "Nintendo key files are never packaged"};
    }
    if (IsFirmwareOrNandName(name) || IsFirmwarePath(ToLower(relative))) {
        return Finding{relative, "firmware", "system firmware and NAND images are never packaged"};
    }
    const auto head = ReadHead(path, std::max<std::size_t>(kKeyTextScanLimit, 16384 + 8));
    if (!head) {
        return Finding{relative, "unreadable", "the file could not be read for validation"};
    }
    const std::size_t text_size = std::min(head->size(), kKeyTextScanLimit);
    if (ContainsKeyText(std::string_view{reinterpret_cast<const char*>(head->data()), text_size})) {
        return Finding{relative, "key-text", "the file contains key material in key-file form"};
    }
    if (const auto signature = MatchContentSignature(*head);
        signature && *signature != allowed_signature) {
        return Finding{relative, "signature", std::string{*signature} + " in an unexpected place"};
    }
    return std::nullopt;
}

bool SetError(std::string* error, std::string text) {
    if (error) {
        *error = std::move(text);
    }
    return false;
}

std::string RandomId() {
    std::random_device device;
    std::mt19937_64 engine{(static_cast<std::uint64_t>(device()) << 32) ^ device() ^
                           static_cast<std::uint64_t>(
                               std::chrono::steady_clock::now().time_since_epoch().count())};
    char buffer[24];
    std::snprintf(buffer, sizeof buffer, "%016llx", static_cast<unsigned long long>(engine()));
    return buffer;
}

bool RenameWithRetry(const fs::path& from, const fs::path& to, std::string* error) {
    std::error_code ec;
    for (int attempt = 0; attempt < 10; ++attempt) {
        if (fs::exists(to, ec)) {
            return SetError(error, "the destination appeared while the package was being moved");
        }
        fs::rename(from, to, ec);
        if (!ec) {
            return true;
        }
        // Indexers and virus scanners briefly hold new files open on Windows.
        std::this_thread::sleep_for(std::chrono::milliseconds(200));
    }
    return SetError(error, "could not move the package into place: " + ec.message());
}

std::string Timestamp() {
    const std::time_t now = std::time(nullptr);
    std::tm local{};
#ifdef _WIN32
    localtime_s(&local, &now);
#else
    localtime_r(&now, &local);
#endif
    char buffer[32];
    std::strftime(buffer, sizeof buffer, "%Y%m%d-%H%M%S", &local);
    return buffer;
}

#ifdef _WIN32
std::optional<fs::path> FinalPath(HANDLE handle) {
    std::wstring buffer(1024, L'\0');
    DWORD size = GetFinalPathNameByHandleW(handle, buffer.data(), static_cast<DWORD>(buffer.size()),
                                           FILE_NAME_NORMALIZED | VOLUME_NAME_DOS);
    if (size >= buffer.size()) {
        buffer.resize(size + 1);
        size = GetFinalPathNameByHandleW(handle, buffer.data(), static_cast<DWORD>(buffer.size()),
                                         FILE_NAME_NORMALIZED | VOLUME_NAME_DOS);
    }
    if (size == 0 || size >= buffer.size()) {
        return std::nullopt;
    }
    buffer.resize(size);
    if (buffer.starts_with(L"\\\\?\\UNC\\")) {
        buffer = L"\\\\" + buffer.substr(8);
    } else if (buffer.starts_with(L"\\\\?\\")) {
        buffer = buffer.substr(4);
    }
    return fs::path{buffer};
}

struct Handle {
    HANDLE value = INVALID_HANDLE_VALUE;
    ~Handle() {
        if (value != INVALID_HANDLE_VALUE) {
            CloseHandle(value);
        }
    }
};
#endif

} // namespace

// ---- names and content ----

std::string NormalizeName(std::string_view name) {
    std::string out{name};
    while (!out.empty() && (out.back() == '.' || out.back() == ' ')) {
        out.pop_back();
    }
    return ToLower(std::move(out));
}

bool IsKeyFileName(std::string_view name) {
    return MatchesAny(kKeyFileNamePatterns, NormalizeName(name));
}

bool IsFirmwareOrNandName(std::string_view name) {
    return MatchesAny(kFirmwareNandNamePatterns, NormalizeName(name));
}

bool IsFirmwarePath(std::string_view relative_lower) {
    return MatchesAny(kFirmwareNandPathPatterns, std::string{relative_lower});
}

bool IsOsMetadataName(std::string_view name) {
    const std::string normalized = NormalizeName(name);
    return std::find(kOsMetadataNames.begin(), kOsMetadataNames.end(), normalized) !=
           kOsMetadataNames.end();
}

bool ContainsKeyText(std::string_view text) {
    std::size_t start = 0;
    while (start < text.size()) {
        std::size_t end = text.find('\n', start);
        if (end == std::string_view::npos) {
            end = text.size();
        }
        std::string_view line = text.substr(start, end - start);
        start = end + 1;
        const std::size_t equals = line.find('=');
        if (equals == std::string_view::npos) {
            continue;
        }
        const auto trim = [](std::string_view part) {
            while (!part.empty() && (part.front() == ' ' || part.front() == '\t')) {
                part.remove_prefix(1);
            }
            while (!part.empty() &&
                   (part.back() == ' ' || part.back() == '\t' || part.back() == '\r')) {
                part.remove_suffix(1);
            }
            return part;
        };
        const std::string name = ToLower(std::string{trim(line.substr(0, equals))});
        const std::string_view value = trim(line.substr(equals + 1));
        std::size_t hex_run = 0;
        while (hex_run < value.size() && IsHex(value[hex_run])) {
            ++hex_run;
        }
        if (hex_run < 32) {
            continue;
        }
        const bool all_hex_name =
            name.size() == 32 && std::all_of(name.begin(), name.end(), IsHex);
        if (all_hex_name && hex_run == 32 && value.size() == 32) {
            return true; // "<rights id> = <title key>"
        }
        if (std::find(kPlainKeyNames.begin(), kPlainKeyNames.end(), name) !=
            kPlainKeyNames.end()) {
            return true;
        }
        if (name.size() > 3 && name[name.size() - 3] == '_' && IsHex(name[name.size() - 2]) &&
            IsHex(name[name.size() - 1])) {
            const std::string stem = name.substr(0, name.size() - 3);
            if (std::find(kIndexedKeyNames.begin(), kIndexedKeyNames.end(), stem) !=
                kIndexedKeyNames.end()) {
                return true;
            }
        }
    }
    return false;
}

std::optional<std::string_view> MatchContentSignature(std::span<const std::uint8_t> head) {
    for (const Signature& signature : kContentSignatures) {
        if (head.size() >= signature.offset + signature.bytes.size() &&
            std::memcmp(head.data() + signature.offset, signature.bytes.data(),
                        signature.bytes.size()) == 0) {
            return signature.name;
        }
    }
    return std::nullopt;
}

// ---- paths ----

bool IsLinkOrReparsePoint(const fs::path& path) {
#ifdef _WIN32
    const DWORD attributes = GetFileAttributesW(path.c_str());
    return attributes != INVALID_FILE_ATTRIBUTES &&
           (attributes & FILE_ATTRIBUTE_REPARSE_POINT) != 0;
#else
    std::error_code ec;
    return fs::is_symlink(fs::symlink_status(path, ec));
#endif
}

bool IsWithin(const fs::path& root, const fs::path& candidate) {
    if (root.empty() || candidate.empty()) {
        return false;
    }
    const fs::path resolved_root = Resolve(root);
    const fs::path resolved = Resolve(candidate);
    auto r = resolved_root.begin();
    auto c = resolved.begin();
    for (; r != resolved_root.end(); ++r, ++c) {
        if (r->empty()) {
            // A trailing separator leaves an empty final element.
            continue;
        }
        if (c == resolved.end() || !ComponentEquals(*r, *c)) {
            return false;
        }
    }
    return true;
}

bool Overlaps(const fs::path& a, const fs::path& b) {
    return IsWithin(a, b) || IsWithin(b, a);
}

std::string Describe(const std::vector<Finding>& findings, std::size_t limit) {
    std::string out;
    for (std::size_t i = 0; i < findings.size() && i < limit; ++i) {
        if (!out.empty()) {
            out += "; ";
        }
        out += findings[i].path + ": " + findings[i].detail + " [" + findings[i].rule + "]";
    }
    if (findings.size() > limit) {
        out += "; and " + std::to_string(findings.size() - limit) + " more";
    }
    return out;
}

// ---- ExeFS planning ----

bool ExeFsPlan::HasMain() const {
    return std::any_of(files.begin(), files.end(), [](const ExeFsFile& file) {
        return file.role == ExeFsRole::Module && file.name == "main";
    });
}

const ExeFsFile* ExeFsPlan::Find(ExeFsRole role) const {
    const auto it = std::find_if(files.begin(), files.end(),
                                 [role](const ExeFsFile& file) { return file.role == role; });
    return it == files.end() ? nullptr : &*it;
}

ExeFsPlan PlanExtractedExeFs(const fs::path& directory) {
    ExeFsPlan plan;
    std::error_code ec;
    if (IsLinkOrReparsePoint(directory) || !fs::is_directory(directory, ec)) {
        plan.rejected.push_back({".", "input", "the ExeFS input is not a plain directory"});
        return plan;
    }
    std::set<std::string> seen;
    std::size_t entries = 0;
    for (fs::directory_iterator it{directory, ec}, end; !ec && it != end; it.increment(ec)) {
        const fs::path path = it->path();
        const std::string raw = Utf8(path.filename());
        const std::string name = NormalizeName(raw);
        if (++entries > 256) {
            plan.rejected.push_back({raw, "too-many", "more entries than any ExeFS holds"});
            break;
        }
        if (IsLinkOrReparsePoint(path)) {
            plan.rejected.push_back({raw, "link", "links and junctions are not followed"});
            continue;
        }
        if (it->is_directory(ec)) {
            plan.ignored.push_back(raw + "/");
            continue;
        }
        if (!it->is_regular_file(ec)) {
            plan.rejected.push_back({raw, "not-a-file", "not a regular file"});
            continue;
        }
        if (IsKeyFileName(name)) {
            plan.rejected.push_back({raw, "key-file", "Nintendo key files are never copied"});
            continue;
        }
        if (IsFirmwareOrNandName(name)) {
            plan.rejected.push_back({raw, "firmware", "firmware and NAND images are never copied"});
            continue;
        }
        if (IsOsMetadataName(name)) {
            plan.ignored.push_back(raw);
            continue;
        }
        if (!seen.insert(name).second) {
            plan.rejected.push_back({raw, "ambiguous", "two entries differ only in case"});
            continue;
        }
        const std::uint64_t size = it->file_size(ec);
        const auto head = ReadHead(path, 0x60);
        if (ec || !head) {
            plan.rejected.push_back({raw, "unreadable", "the file could not be read"});
            continue;
        }
        const auto accept = [&](ExeFsRole role, std::string canonical) {
            plan.files.push_back({path, std::move(canonical), role, size});
        };
        const auto reject = [&](std::string detail) {
            plan.rejected.push_back({raw, "invalid-format", std::move(detail)});
        };
        if (std::find(kModuleNames.begin(), kModuleNames.end(), name) != kModuleNames.end()) {
            if (size < kNsoHeaderSize || !StartsWith(*head, "NSO0")) {
                reject("an ExeFS module must be an NSO executable");
            } else {
                accept(ExeFsRole::Module, name);
            }
        } else if (name == "main.npdm") {
            if (!StartsWith(*head, "META")) {
                reject("main.npdm must be NPDM metadata");
            } else {
                accept(ExeFsRole::Npdm, name);
            }
        } else if (name == "romfs.bin" || name == "romfs") {
            if (size < kRomFsHeaderSize || ReadU64(*head, 0) != kRomFsHeaderSize) {
                reject("the RomFS image has no RomFS header");
            } else if (plan.Find(ExeFsRole::RomFs)) {
                plan.rejected.push_back({raw, "ambiguous", "both romfs and romfs.bin are present"});
            } else {
                accept(ExeFsRole::RomFs, "romfs.bin");
            }
        } else if (name == "control.nca") {
            // The header is encrypted; the exporter validates it with the
            // installed keys against the selected title before packaging it.
            if (size < kNcaHeaderSize) {
                reject("control.nca is too small to be an NCA");
            } else {
                accept(ExeFsRole::ControlNca, name);
            }
        } else if (name == "control.nacp") {
            if (size != kNacpSize) {
                reject("control.nacp must be exactly 16 KiB");
            } else {
                accept(ExeFsRole::ControlNacp, name);
            }
        } else if (std::regex_match(name, std::regex{R"(^icon_[a-z]+\.dat$)"})) {
            if (head->size() < 3 || (*head)[0] != 0xFF || (*head)[1] != 0xD8 || (*head)[2] != 0xFF) {
                reject("an icon must be a JPEG image");
            } else {
                accept(ExeFsRole::Icon, name);
            }
        } else {
            plan.rejected.push_back(
                {raw, "unexpected-file", "not a file any ExeFS loader reads; remove it or "
                                         "export from a folder holding only the game's ExeFS"});
        }
    }
    if (ec) {
        plan.rejected.push_back({".", "unreadable", "the directory could not be listed"});
    }
    if (plan.rejected.empty() && !plan.HasMain()) {
        plan.rejected.push_back({"main", "missing", "an ExeFS needs a main module"});
    }
    return plan;
}

// ---- copying ----

bool CopyFileNoFollow(const fs::path& source_root, const fs::path& source,
                      const fs::path& destination, std::string* error, const Progress& progress) {
    std::error_code ec;
    if (fs::exists(fs::symlink_status(destination, ec))) {
        return SetError(error, "destination already exists: " + Utf8(destination.filename()));
    }
    const fs::path root = Resolve(source_root);
#ifdef _WIN32
    Handle in;
    in.value = CreateFileW(source.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                           FILE_FLAG_OPEN_REPARSE_POINT | FILE_FLAG_SEQUENTIAL_SCAN, nullptr);
    if (in.value == INVALID_HANDLE_VALUE) {
        return SetError(error, "cannot open " + Utf8(source.filename()));
    }
    BY_HANDLE_FILE_INFORMATION info{};
    if (!GetFileInformationByHandle(in.value, &info) ||
        (info.dwFileAttributes & (FILE_ATTRIBUTE_REPARSE_POINT | FILE_ATTRIBUTE_DIRECTORY)) != 0) {
        return SetError(error, Utf8(source.filename()) + " is a link or not a regular file");
    }
    // The checked name could have been swapped for a link to somewhere else
    // between planning and opening; the open handle says where it really is.
    const auto real = FinalPath(in.value);
    if (!real || !IsWithin(root, *real)) {
        return SetError(error, Utf8(source.filename()) + " resolves outside its source folder");
    }
    const std::uint64_t total =
        (static_cast<std::uint64_t>(info.nFileSizeHigh) << 32) | info.nFileSizeLow;
    Handle out;
    out.value = CreateFileW(destination.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_NEW,
                            FILE_ATTRIBUTE_NORMAL, nullptr);
    if (out.value == INVALID_HANDLE_VALUE) {
        return SetError(error, "cannot create " + Utf8(destination.filename()));
    }
    std::vector<char> buffer(4u << 20);
    std::uint64_t done = 0;
    while (true) {
        DWORD read = 0;
        if (!ReadFile(in.value, buffer.data(), static_cast<DWORD>(buffer.size()), &read, nullptr)) {
            return SetError(error, "read failed for " + Utf8(source.filename()));
        }
        if (read == 0) {
            break;
        }
        DWORD written = 0;
        if (!WriteFile(out.value, buffer.data(), read, &written, nullptr) || written != read) {
            return SetError(error, "write failed for " + Utf8(destination.filename()));
        }
        done += read;
        if (progress) {
            progress(done, total);
        }
    }
    if (done != total || !FlushFileBuffers(out.value)) {
        return SetError(error, "copy of " + Utf8(source.filename()) + " did not complete");
    }
    return true;
#else
    const int in = open(source.c_str(), O_RDONLY | O_NOFOLLOW | O_CLOEXEC);
    if (in < 0) {
        return SetError(error, "cannot open " + Utf8(source.filename()) + " without following links");
    }
    struct stat info {};
    struct stat by_name {};
    const fs::path real = fs::canonical(source, ec);
    // fstat pins what was opened; the canonical name must name the same file
    // and lie inside the root. A parent swapped in between is caught here.
    if (fstat(in, &info) != 0 || !S_ISREG(info.st_mode) || ec || !IsWithin(root, real) ||
        stat(real.c_str(), &by_name) != 0 || by_name.st_dev != info.st_dev ||
        by_name.st_ino != info.st_ino) {
        close(in);
        return SetError(error, Utf8(source.filename()) + " is not a regular file inside its source");
    }
    const int out = open(destination.c_str(), O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW | O_CLOEXEC,
                         0644);
    if (out < 0) {
        close(in);
        return SetError(error, "cannot create " + Utf8(destination.filename()));
    }
    std::vector<char> buffer(4u << 20);
    std::uint64_t done = 0;
    const std::uint64_t total = static_cast<std::uint64_t>(info.st_size);
    bool ok = true;
    while (ok) {
        const ssize_t read_bytes = read(in, buffer.data(), buffer.size());
        if (read_bytes <= 0) {
            ok = read_bytes == 0;
            break;
        }
        ssize_t offset = 0;
        while (offset < read_bytes) {
            const ssize_t written = write(out, buffer.data() + offset,
                                          static_cast<std::size_t>(read_bytes - offset));
            if (written <= 0) {
                ok = false;
                break;
            }
            offset += written;
        }
        done += static_cast<std::uint64_t>(read_bytes);
        if (progress) {
            progress(done, total);
        }
    }
    ok = ok && done == total && fsync(out) == 0;
    close(in);
    close(out);
    return ok || SetError(error, "copy of " + Utf8(source.filename()) + " did not complete");
#endif
}

bool CopyTreeNoFollow(const fs::path& source, const fs::path& destination, std::string* error,
                      const TreeLimits& limits) {
    std::error_code ec;
    if (IsLinkOrReparsePoint(source) || !fs::is_directory(source, ec)) {
        return SetError(error, Utf8(source.filename()) + " is not a plain directory");
    }
    if (fs::exists(fs::symlink_status(destination, ec))) {
        return SetError(error, "destination already exists: " + Utf8(destination.filename()));
    }
    if (Overlaps(source, destination)) {
        return SetError(error, "source and destination overlap");
    }
    if (!fs::create_directories(destination, ec)) {
        return SetError(error, "cannot create " + Utf8(destination.filename()));
    }
    std::size_t files = 0;
    std::uint64_t bytes = 0;
    fs::recursive_directory_iterator it{source, fs::directory_options::none, ec};
    for (const fs::recursive_directory_iterator end; !ec && it != end; it.increment(ec)) {
        const fs::path path = it->path();
        const std::string relative = Relative(source, path);
        if (static_cast<std::size_t>(it.depth()) >= limits.max_depth) {
            return SetError(error, relative + ": nested deeper than a save or cache holds");
        }
        if (IsLinkOrReparsePoint(path)) {
            return SetError(error, relative + ": links and junctions are not copied");
        }
        const fs::path target = destination / fs::relative(path, source, ec);
        if (ec) {
            break;
        }
        if (it->is_directory(ec)) {
            if (!fs::create_directory(target, ec)) {
                return SetError(error, "cannot create " + relative);
            }
            continue;
        }
        if (!it->is_regular_file(ec)) {
            return SetError(error, relative + ": not a regular file");
        }
        if (const auto finding = CheckFileContent(path, relative)) {
            return SetError(error, relative + ": " + finding->detail);
        }
        bytes += it->file_size(ec);
        if (++files > limits.max_files || bytes > limits.max_bytes) {
            return SetError(error, "more data than an export copies for one title");
        }
        if (!CopyFileNoFollow(source, path, target, error)) {
            return false;
        }
    }
    if (ec) {
        return SetError(error, "cannot list " + Utf8(source.filename()) + ": " + ec.message());
    }
    return true;
}

bool RemoveTreeNoFollow(const fs::path& path, std::string* error) {
    std::error_code ec;
    const auto status = fs::symlink_status(path, ec);
    if (ec || !fs::exists(status)) {
        return true;
    }
    if (IsLinkOrReparsePoint(path) || !fs::is_directory(status)) {
#ifdef _WIN32
        // A junction or directory symlink is removed as a directory entry,
        // which never touches its target.
        if (fs::is_directory(status) || IsLinkOrReparsePoint(path)) {
            if (RemoveDirectoryW(path.c_str()) || DeleteFileW(path.c_str())) {
                return true;
            }
            return SetError(error, "cannot remove " + Utf8(path.filename()));
        }
#endif
        fs::remove(path, ec);
        return !ec || SetError(error, "cannot remove " + Utf8(path.filename()));
    }
    std::vector<fs::path> children;
    for (fs::directory_iterator it{path, ec}, end; !ec && it != end; it.increment(ec)) {
        children.push_back(it->path());
    }
    if (ec) {
        return SetError(error, "cannot list " + Utf8(path.filename()));
    }
    for (const auto& child : children) {
        if (!RemoveTreeNoFollow(child, error)) {
            return false;
        }
    }
    fs::remove(path, ec);
    return !ec || SetError(error, "cannot remove " + Utf8(path.filename()));
}

// ---- staging ----

std::optional<Staging> CreateStaging(const fs::path& output_dir, std::string* error) {
    std::error_code ec;
    fs::create_directories(output_dir, ec);
    if (IsLinkOrReparsePoint(output_dir) || !fs::is_directory(output_dir, ec)) {
        SetError(error, "the output folder is not a plain directory");
        return std::nullopt;
    }
    for (int attempt = 0; attempt < 8; ++attempt) {
        Staging staging;
        staging.output_dir = output_dir;
        staging.id = RandomId().substr(0, 8);
        const std::string base = ".suyu-export-" + staging.id;
        staging.root = output_dir / base;
        staging.work = output_dir / (base + ".work");
        const fs::path marker = output_dir / (base + ".staging");
        if (fs::exists(fs::symlink_status(staging.root, ec)) ||
            fs::exists(fs::symlink_status(staging.work, ec)) ||
            fs::exists(fs::symlink_status(marker, ec))) {
            continue;
        }
        {
            std::ofstream out(marker, std::ios::binary | std::ios::trunc);
            out << "suyu export staging " << kPolicyVersion << ' ' << staging.id << '\n';
            if (!out) {
                SetError(error, "cannot write in the output folder");
                return std::nullopt;
            }
        }
        if (!fs::create_directory(staging.root, ec) || !fs::create_directory(staging.work, ec)) {
            RemoveStaging(staging, nullptr);
            SetError(error, "cannot create the staging folder");
            return std::nullopt;
        }
        return staging;
    }
    SetError(error, "cannot choose a staging folder name");
    return std::nullopt;
}

bool RemoveStaging(const Staging& staging, std::string* error) {
    std::error_code ec;
    const fs::path marker = staging.output_dir / (".suyu-export-" + staging.id + ".staging");
    std::ifstream in(marker, std::ios::binary);
    std::string line;
    std::getline(in, line);
    in.close();
    if (staging.id.empty() || line.find(staging.id) == std::string::npos) {
        return SetError(error, "not removing a folder this export does not own");
    }
    bool ok = RemoveTreeNoFollow(staging.work, error);
    if (fs::exists(fs::symlink_status(staging.root, ec))) {
        ok = RemoveTreeNoFollow(staging.root, error) && ok;
    }
    fs::remove(marker, ec);
    return ok;
}

Existing ClassifyDestination(const fs::path& destination) {
    std::error_code ec;
    const auto status = fs::symlink_status(destination, ec);
    if (ec || !fs::exists(status)) {
        return Existing::None;
    }
    if (IsLinkOrReparsePoint(destination) || !fs::is_directory(status)) {
        return Existing::Foreign;
    }
    std::ifstream manifest(destination / std::string{kExportManifestName}, std::ios::binary);
    if (manifest) {
        std::string text(4096, '\0');
        manifest.read(text.data(), static_cast<std::streamsize>(text.size()));
        text.resize(static_cast<std::size_t>(manifest.gcount()));
        if (text.find(std::string{"\""} + std::string{kExportManifestSchema} + "\"") !=
            std::string::npos) {
            return Existing::ExporterManaged;
        }
    }
    for (const char* readme : {"README_NATIVE_EXPORT.txt", "Contents/README_NATIVE_EXPORT.txt"}) {
        if (fs::is_regular_file(destination / readme, ec)) {
            return Existing::LegacyExport;
        }
    }
    return Existing::Foreign;
}

PromoteResult Promote(const Staging& staging, const fs::path& destination, ConflictPolicy policy) {
    PromoteResult result;
    std::error_code ec;
    if (!IsWithin(staging.output_dir, destination) ||
        !ComponentEquals(Resolve(destination.parent_path()), Resolve(staging.output_dir))) {
        result.error = "the package must be placed directly in the output folder";
        return result;
    }
    const Existing existing = ClassifyDestination(destination);
    fs::path target = destination;
    if (existing != Existing::None) {
        if (policy == ConflictPolicy::Fail) {
            result.conflict = true;
            result.error = "a folder with this name already exists";
            return result;
        }
        if (policy == ConflictPolicy::ReplaceWithBackup && existing == Existing::Foreign) {
            result.conflict = true;
            result.error = "the existing folder was not made by the exporter, so it is not replaced";
            return result;
        }
        if (policy == ConflictPolicy::KeepBoth) {
            const std::string stem = Utf8(destination.filename());
            for (int n = 2; n < 1000; ++n) {
                const fs::path candidate =
                    destination.parent_path() / fs::path{std::u8string{
                        reinterpret_cast<const char8_t*>(stem.data()), stem.size()}}
                                                    .concat(" (" + std::to_string(n) + ")");
                if (!fs::exists(fs::symlink_status(candidate, ec))) {
                    target = candidate;
                    break;
                }
            }
            if (target == destination) {
                result.error = "no free folder name";
                return result;
            }
        } else {
            fs::path backup = destination;
            backup += ".previous-" + Timestamp();
            while (fs::exists(fs::symlink_status(backup, ec))) {
                backup += "-" + RandomId().substr(0, 4);
            }
            if (!RenameWithRetry(destination, backup, &result.error)) {
                return result;
            }
            result.backup_path = backup;
        }
    }
    if (!RenameWithRetry(staging.root, target, &result.error)) {
        if (!result.backup_path.empty()) {
            std::string restore_error;
            if (!RenameWithRetry(result.backup_path, destination, &restore_error)) {
                result.error += "; the previous package is still at " +
                                Utf8(result.backup_path.filename());
            } else {
                result.backup_path.clear();
            }
        }
        return result;
    }
    result.ok = true;
    result.final_path = target;
    return result;
}

// ---- local export validation ----

bool IsGameDataInAotCache(std::string_view relative_lower) {
    // relative_lower starts at "aot_cache/". The analysed modules (exefs/nso), the
    // bundled segments of a standalone runner (<module>/data), that runner itself
    // (<module>/main.c) and debug dumps of guest code (debug/) are copies of the game's
    // own executables, or a way to run them without suyu and the user's keys.
    const auto parts_of = [](std::string_view text) {
        std::vector<std::string_view> parts;
        while (!text.empty()) {
            const auto slash = text.find('/');
            parts.push_back(text.substr(0, slash));
            if (slash == std::string_view::npos) {
                break;
            }
            text.remove_prefix(slash + 1);
        }
        return parts;
    };
    const auto parts = parts_of(relative_lower);
    if (parts.size() < 2 || parts[0] != "aot_cache") {
        return false;
    }
    if (parts[1] == "debug") {
        return true;
    }
    if (parts.size() >= 3 && parts[1] == "exefs" && parts[2] == "nso") {
        return true;
    }
    // aot_cache/exefs/<module>/data/... and aot_cache/exefs/<module>/main.c
    if (parts.size() >= 4 && parts[1] == "exefs" && parts[3] == "data") {
        return true;
    }
    return parts.size() == 4 && parts[1] == "exefs" && parts[3] == "main.c";
}

bool ManifestDeclaresPortable(std::string_view manifest_text) {
    static const std::regex declared{R"re("package_type"\s*:\s*"portable")re"};
    return std::regex_search(manifest_text.begin(), manifest_text.end(), declared);
}

std::vector<Finding> ValidateLocalExport(const fs::path& root,
                                         const LocalExportExpectation& expect) {
    std::vector<Finding> findings;
    std::error_code ec;
    // Sealed game files belong only to a portable export that says it is one.
    bool manifest_portable = false;
    if (const auto manifest =
            ReadHead(root / fs::path{std::string{kExportManifestName}}, kKeyTextScanLimit)) {
        manifest_portable = ManifestDeclaresPortable(
            std::string_view{reinterpret_cast<const char*>(manifest->data()), manifest->size()});
    }
    const bool portable =
        expect.portable && manifest_portable && expect.platform == Platform::Windows;
    if (expect.portable != manifest_portable) {
        findings.push_back({std::string{kExportManifestName}, "package-type",
                            expect.portable ? "the manifest does not declare a portable export"
                                            : "the manifest declares a portable export"});
    }
    const std::string game_dir = NormalizeName(kPortableGameDir);
    const std::regex sealed_update{R"(update-[0-9]{1,2}\.sealed)"};
    const std::regex sealed_dlc{R"(dlc-[0-9]{1,4}\.sealed)"};
    bool has_base = false;
    bool has_seal = false;
    const std::string title_lower = ToLower(expect.title_id_hex);
    std::set<std::string> dlls;
    for (const auto& dll : expect.runtime_dlls) {
        dlls.insert(NormalizeName(dll));
    }
    const std::string launcher = NormalizeName(expect.package_name + ".exe");
    const std::regex hex16{R"([0-9a-f]{16})"};
    const std::regex hex32{R"([0-9a-f]{32})"};

    // The prefix that holds the package's own files; Linux and macOS bundles
    // keep them one level down.
    const std::string bin = expect.platform == Platform::Linux   ? "usr/bin/"
                            : expect.platform == Platform::MacOS ? "contents/resources/"
                                                                 : "";

    const auto split = [](const std::string& relative) {
        std::vector<std::string> parts;
        std::size_t start = 0;
        while (start <= relative.size()) {
            const std::size_t slash = relative.find('/', start);
            parts.push_back(relative.substr(start, slash == std::string::npos ? std::string::npos
                                                                              : slash - start));
            if (slash == std::string::npos) {
                break;
            }
            start = slash + 1;
        }
        return parts;
    };

    // Directories that may exist, as lower-cased relative paths.
    const auto allowed_directory = [&](const std::string& rel) {
        static const std::set<std::string> fixed{
            "user", "user/config", "user/nand", "user/nand/user", "user/nand/user/save",
            "user/cache", "user/cache/shader", "licenses"};
        if (fixed.count(rel)) {
            return true;
        }
        if (portable && rel == game_dir) {
            return true;
        }
        const auto parts = split(rel);
        if (expect.platform == Platform::Windows && rel == "mods") {
            return true;
        }
        if (expect.platform == Platform::Linux && (rel == "usr" || rel == "usr/bin")) {
            return true;
        }
        if (expect.platform == Platform::MacOS && (rel == "contents" || rel == "contents/resources")) {
            return true;
        }
        if (expect.allow_aot_cache && (rel + "/").starts_with(bin + "aot_cache/") &&
            !IsGameDataInAotCache(rel.substr(bin.size()) + "/")) {
            return true;
        }
        if (parts.size() >= 5 && parts[0] == "user" && parts[1] == "nand" && parts[2] == "user" &&
            parts[3] == "save" && std::regex_match(parts[4], hex16)) {
            if (parts.size() == 5) {
                return true;
            }
            if (!std::regex_match(parts[5], hex32)) {
                return false;
            }
            return parts.size() == 6 || parts[6] == title_lower;
        }
        if (parts.size() >= 4 && parts[0] == "user" && parts[1] == "cache" &&
            parts[2] == "shader") {
            return parts[3] == title_lower;
        }
        return false;
    };

    const auto allowed_file = [&](const std::string& rel, std::string_view& signature) {
        const auto parts = split(rel);
        const std::string& name = parts.back();
        if (parts.size() == 1) {
            if (name == "readme_native_export.txt" || name == NormalizeName(kExportManifestName)) {
                return true;
            }
            if (expect.platform == Platform::Windows) {
                return name == launcher || name == "launch.bat" || name == "game_source.txt" ||
                       name == "aot_manifest.json" || name == "discord.ini" || dlls.count(name);
            }
            return false;
        }
        if (portable && parts.size() == 2 && parts[0] == game_dir) {
            if (name == NormalizeName(kPortableSealName)) {
                has_seal = true;
                return true;
            }
            if (name == NormalizeName(kPortableBaseName)) {
                has_base = true;
                return true;
            }
            return std::regex_match(name, sealed_update) || std::regex_match(name, sealed_dlc);
        }
        if (parts.size() == 2 && parts[0] == "licenses") {
            return name == "license.txt" || name == "third-party-notices.txt" ||
                   name == "source.txt";
        }
        if (expect.platform == Platform::MacOS && rel == "contents/readme_native_export.txt") {
            return true;
        }
        if (expect.platform != Platform::Windows && rel == bin + "game_source.txt") {
            return true;
        }
        if (rel == "user/config/sdl2-config.ini" || rel == "user/config/suyu-install.txt" ||
            rel == "user/config/game-source.ini") {
            return true;
        }
        // The generated project only: never the game's modules, segments or dumps.
        if (expect.allow_aot_cache && rel.starts_with(bin + "aot_cache/")) {
            return !IsGameDataInAotCache(rel.substr(bin.size()));
        }
        // A file somewhere inside this title's save folder.
        if (parts.size() >= 8 && parts[0] == "user" && parts[1] == "nand" && parts[2] == "user" &&
            parts[3] == "save" && std::regex_match(parts[4], hex16) &&
            std::regex_match(parts[5], hex32) && parts[6] == title_lower) {
            return true;
        }
        if (parts.size() >= 5 && parts[0] == "user" && parts[1] == "cache" &&
            parts[2] == "shader" && parts[3] == title_lower) {
            return true;
        }
        return false;
    };

    fs::recursive_directory_iterator it{root, fs::directory_options::none, ec};
    for (const fs::recursive_directory_iterator end; !ec && it != end; it.increment(ec)) {
        const fs::path path = it->path();
        const std::string relative = Relative(root, path);
        std::string lower;
        for (const auto& part : split(relative)) {
            lower += (lower.empty() ? "" : "/") + NormalizeName(part);
        }
        if (IsLinkOrReparsePoint(path)) {
            findings.push_back({relative, "link", "links and junctions are never packaged"});
            it.disable_recursion_pending();
            continue;
        }
        if (it->is_directory(ec)) {
            if (!allowed_directory(lower)) {
                findings.push_back({relative, "unexpected", "the exporter does not create this folder"});
                it.disable_recursion_pending();
            }
            continue;
        }
        if (!it->is_regular_file(ec)) {
            findings.push_back({relative, "not-a-file", "not a regular file"});
            continue;
        }
        std::string_view signature;
        if (!allowed_file(lower, signature)) {
            findings.push_back({relative, "unexpected", "the exporter does not write this file"});
            continue;
        }
        const std::string extension = ToLower(Utf8(path.extension()));
        if (std::find(kGameContainerExtensions.begin(), kGameContainerExtensions.end(),
                      extension) != kGameContainerExtensions.end()) {
            findings.push_back({relative, "game-container", "game containers are never packaged"});
            continue;
        }
        if (auto finding = CheckFileContent(path, relative, signature)) {
            findings.push_back(std::move(*finding));
        }
    }
    if (ec) {
        findings.push_back({".", "unreadable", "the package could not be listed: " + ec.message()});
    }
    if (portable && (!has_base || !has_seal)) {
        findings.push_back({std::string{kPortableGameDir}, "portable-incomplete",
                            "a portable export needs its sealed game file and seal.json"});
    }
    return findings;
}

std::span<const std::string_view> ExportableSettings() {
    return kExportableSettings;
}

bool IsExportableSettingKey(std::string_view key) {
    constexpr std::string_view kDefaultSuffix = "/default";
    if (key.ends_with(kDefaultSuffix)) {
        key.remove_suffix(kDefaultSuffix.size());
    }
    const auto list = ExportableSettings();
    return std::find(list.begin(), list.end(), key) != list.end();
}

std::optional<fs::path> AcceptInstalledRoot(const fs::path& package_dir,
                                            const fs::path& candidate) {
    if (candidate.empty() || package_dir.empty() || IsWithin(package_dir, candidate)) {
        return std::nullopt;
    }
    return candidate;
}

} // namespace Common::PackagePolicy
