// SPDX-FileCopyrightText: Copyright 2026 suyu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// Package-policy validation shared by the game exporter and its launcher.
//
// Three outputs are kept apart:
//  - PUBLIC_RELEASE: what the project ships. Checked by
//    tools/package_policy/scan_release.py, which reads the same rules from
//    tools/package_policy/policy.json (tests/package_policy/test_policy_sync.py
//    keeps the tables below and that file in step).
//  - LOCAL_GAME_EXPORT: a package the exporter builds on the user's machine from
//    a game the user selected. It holds translated code and reads the game file,
//    so it is never an official artifact, but it must never hold keys, firmware
//    or files nobody selected. Checked here.
//  - SHARED_COVERAGE: see core/arm/recomp/recomp_gaps.h.
//
// These are project distribution controls. Passing them says what a package
// contains; it does not establish ownership, permission or legal clearance.
//
// Standard library only: the tests compile this file on its own.

#include <cstdint>
#include <filesystem>
#include <functional>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace Common::PackagePolicy {

inline constexpr std::string_view kPolicyVersion = "suyu-package-policy-1";
inline constexpr std::string_view kExportManifestName = "export-package.json";
inline constexpr std::string_view kExportManifestSchema = "suyu-local-game-export";
inline constexpr std::size_t kKeyTextScanLimit = 64 * 1024;
/// "package_type" in the export manifest of a portable export, which carries the user's game
/// file, installed update and DLC NCAs, unchanged and sealed to the exporting console's keys.
inline constexpr std::string_view kPortablePackageType = "portable";
/// Where a portable export keeps its sealed files, and their description.
inline constexpr std::string_view kPortableGameDir = "game";
inline constexpr std::string_view kPortableSealName = "seal.json";
inline constexpr std::string_view kPortableBaseName = "base.sealed";

/// True when @p title_id is an add-on content (DLC) title of the game @p program_id: the same
/// base title, the add-on offset 0x1000 and an add-on index from 1 to 0x7FF.
constexpr bool IsAddOnContentOf(std::uint64_t title_id, std::uint64_t program_id) {
    constexpr std::uint64_t kBaseMask = 0xFFFFFFFFFFFFE000;
    const std::uint64_t low = title_id & ~kBaseMask;
    return program_id != 0 && (title_id & kBaseMask) == (program_id & kBaseMask) &&
           low > 0x1000 && low <= 0x17FF;
}

/// Lower-cases ASCII and drops the trailing dots and spaces Windows ignores.
std::string NormalizeName(std::string_view name);
/// prod/title/console/dev.keys and their autogenerated or renamed variants.
bool IsKeyFileName(std::string_view name);
/// NAND partitions, BOOT0/1, PRODINFO, package1/2 and similar.
bool IsFirmwareOrNandName(std::string_view name);
/// A lower-cased relative path (forward slashes) inside a NAND system area.
bool IsFirmwarePath(std::string_view relative_lower);
/// desktop.ini, Thumbs.db, .DS_Store: never copied, never an error.
bool IsOsMetadataName(std::string_view name);
/// A line of the form "<known key name> = <hex>" or "<32 hex> = <32 hex>".
bool ContainsKeyText(std::string_view text);
/// The name of a Nintendo container/executable signature found in `head`.
std::optional<std::string_view> MatchContentSignature(std::span<const std::uint8_t> head);

/// A symlink, junction or any other reparse point. Never follows it.
bool IsLinkOrReparsePoint(const std::filesystem::path& path);
/// True when `candidate` is `root` or lies below it, compared by path component
/// after both are made absolute and resolved. Case-insensitive on Windows.
bool IsWithin(const std::filesystem::path& root, const std::filesystem::path& candidate);
/// Either path lies within the other.
bool Overlaps(const std::filesystem::path& a, const std::filesystem::path& b);

struct Finding {
    std::string path; ///< relative to the checked root, forward slashes
    std::string rule;
    std::string detail;
};
std::string Describe(const std::vector<Finding>& findings, std::size_t limit = 8);

// ---- Extracted ExeFS input ----

enum class ExeFsRole { Module, Npdm, RomFs, ControlNca, ControlNacp, Icon };

struct ExeFsFile {
    std::filesystem::path source;
    std::string name; ///< canonical name to write, e.g. "main"
    ExeFsRole role;
    std::uint64_t size = 0;
};

struct ExeFsPlan {
    std::vector<ExeFsFile> files;
    std::vector<std::string> ignored; ///< directories and OS metadata, never copied
    std::vector<Finding> rejected;
    bool HasMain() const;
    bool Ok() const {
        return rejected.empty() && HasMain();
    }
    const ExeFsFile* Find(ExeFsRole role) const;
};

/// Classifies every entry of an extracted ExeFS directory by the role the
/// loaders give it, validating each file's format. Anything else - unknown
/// siblings, key files, firmware, links, case collisions - is rejected.
ExeFsPlan PlanExtractedExeFs(const std::filesystem::path& directory);

// ---- Copying ----

using Progress = std::function<void(std::uint64_t done, std::uint64_t total)>;

/// Copies one regular file without following links. `source` must resolve
/// inside `source_root` when opened (checked on the open handle where the
/// platform allows it), and `destination` must not exist yet.
bool CopyFileNoFollow(const std::filesystem::path& source_root,
                      const std::filesystem::path& source,
                      const std::filesystem::path& destination, std::string* error,
                      const Progress& progress = {});

struct TreeLimits {
    std::size_t max_files = 200000;
    std::size_t max_depth = 16;
    std::uint64_t max_bytes = 64ull << 30;
};

/// Copies a directory tree that must not exist at `destination` yet. Links,
/// junctions, key files, firmware and key-shaped text fail the copy.
bool CopyTreeNoFollow(const std::filesystem::path& source, const std::filesystem::path& destination,
                      std::string* error, const TreeLimits& limits = {});

/// Removes a tree, deleting links as links rather than what they point at.
bool RemoveTreeNoFollow(const std::filesystem::path& path, std::string* error);

// ---- Staging and promotion ----

/// A directory this run owns: <output>/.suyu-export-<id>, marked by the file
/// <output>/.suyu-export-<id>.staging. The marker sits beside the directory so
/// it never ends up in a promoted package.
struct Staging {
    std::filesystem::path output_dir;
    std::filesystem::path root;
    std::filesystem::path work; ///< scratch space next to it, never promoted
    std::string id;
};
std::optional<Staging> CreateStaging(const std::filesystem::path& output_dir, std::string* error);
/// Deletes the staging directories only when the marker for this id is present.
bool RemoveStaging(const Staging& staging, std::string* error);

enum class Existing { None, ExporterManaged, LegacyExport, Foreign };
Existing ClassifyDestination(const std::filesystem::path& destination);

enum class ConflictPolicy { Fail, KeepBoth, ReplaceWithBackup };

struct PromoteResult {
    bool ok = false;
    bool conflict = false;
    std::filesystem::path final_path;
    std::filesystem::path backup_path; ///< the previous package, kept, never deleted
    std::string error;
};
/// Moves a validated staging package to `destination`. An existing
/// destination is never merged into: Fail reports a conflict, KeepBoth picks
/// "<name> (N)", and ReplaceWithBackup renames an exporter-managed or legacy
/// export aside (keeping its saves) before moving the new one in, restoring
/// it if that move fails. A foreign directory is never replaced.
PromoteResult Promote(const Staging& staging, const std::filesystem::path& destination,
                      ConflictPolicy policy);

// ---- Local game export validation ----

enum class Platform { Windows, Linux, MacOS };

struct LocalExportExpectation {
    Platform platform = Platform::Windows;
    std::string package_name;              ///< launcher is <package_name>.exe on Windows
    std::string title_id_hex;              ///< 16 upper-case hex digits
    bool allow_aot_cache = false;          ///< Source-format exports keep the C project
    std::vector<std::string> runtime_dlls; ///< names allowed beside the launcher
    /// A portable export (Windows layout only): game/ may hold the sealed game file, sealed
    /// update NCAs (update-<n>.sealed), sealed DLC NCAs (dlc-<n>.sealed) and seal.json, and
    /// the manifest must say so.
    bool portable = false;
};

/// True for a path under aot_cache/ that holds the game's own executables or a way to
/// run them outside suyu: analysed modules, bundled segments, the standalone runner
/// and guest-code dumps. `relative_lower` is lower-case and starts with "aot_cache/".
bool IsGameDataInAotCache(std::string_view relative_lower);

/// True when the manifest text declares the portable package type.
bool ManifestDeclaresPortable(std::string_view manifest_text);

/// Walks a complete staging package and reports anything the exporter does
/// not produce: links, key files or key-shaped text, firmware, stray Nintendo
/// containers, and files outside the documented layout. Sealed game files are
/// accepted only in a portable export whose manifest declares it; a container
/// that is not sealed is reported wherever it is.
std::vector<Finding> ValidateLocalExport(const std::filesystem::path& root,
                                         const LocalExportExpectation& expect);

/// The settings an exported package may carry, as "Section/label" pairs in the
/// form QSettings reads them. Everything else stays behind: paths, devices,
/// accounts, web service credentials, debugging and unsafe CPU/GPU options.
std::span<const std::string_view> ExportableSettings();
bool IsExportableSettingKey(std::string_view key);

// ---- Launcher-side resolution ----

/// The installed suyu root an exported package reads keys and firmware from,
/// rejected when it would alias back into the package itself.
std::optional<std::filesystem::path> AcceptInstalledRoot(const std::filesystem::path& package_dir,
                                                         const std::filesystem::path& candidate);

} // namespace Common::PackagePolicy
