// Writes the two runtimes the differential test links together: ABI 6 (FM1)
// as-is, and the pristine ABI 5 runtime plus a header that renames every
// function it defines to abi5_*, so both can live in one binary.
#include <cctype>
#include <filesystem>
#include <fstream>
#include <set>
#include <string>
#include "core/recompiler/arm64_to_c.h"

namespace {

bool Write(const std::filesystem::path& path, const std::string& text) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary);
    out.write(text.data(), static_cast<std::streamsize>(text.size()));
    return static_cast<bool>(out);
}

// Names of the non-static functions a runtime text defines at file scope: a
// line that starts a declaration, is not static, and opens recomp_<name>(.
void CollectDefinitions(const std::string& text, std::set<std::string>& names) {
    size_t line = 0;
    while (line < text.size()) {
        const size_t end = text.find('\n', line);
        const std::string row = text.substr(line, end == std::string::npos ? std::string::npos
                                                                             : end - line);
        line = end == std::string::npos ? text.size() : end + 1;
        if (row.empty() || !std::isalpha(static_cast<unsigned char>(row[0])) ||
            row.rfind("static", 0) == 0 || row.rfind("typedef", 0) == 0 ||
            row.find('{') == std::string::npos) {
            continue;
        }
        const size_t at = row.find("recomp_");
        if (at == std::string::npos) {
            continue;
        }
        size_t stop = at;
        while (stop < row.size() &&
               (std::isalnum(static_cast<unsigned char>(row[stop])) || row[stop] == '_')) {
            ++stop;
        }
        size_t paren = stop;
        while (paren < row.size() && row[paren] == ' ') {
            ++paren; // "recomp_load8 (" is aligned with a space
        }
        if (paren < row.size() && row[paren] == '(') {
            names.insert(row.substr(at, stop - at));
        }
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        return 2;
    }
    const std::filesystem::path out = argv[1];
    const std::string fm_h = suyu::recomp::BuildRuntimeH(true);
    const std::string fm_c = suyu::recomp::BuildRuntimeC(true);
    const std::string abi5_h = suyu::recomp::BuildRuntimeH(false);
    const std::string abi5_c = suyu::recomp::BuildRuntimeC(false);
    if (fm_c.find("recomp_load64_slow(") == std::string::npos ||
        abi5_c.find("recomp_fm_entry") != std::string::npos) {
        return 3;
    }
    std::set<std::string> names;
    CollectDefinitions(abi5_c, names);
    CollectDefinitions(abi5_h, names);
    if (!names.count("recomp_load64") || !names.count("recomp_stp32")) {
        return 4;
    }
    std::string rename = "/* generated by fmdiff_gen */\n";
    for (const auto& name : names) {
        rename += "#define " + name + " abi5_" + name + "\n";
    }
    const bool ok = Write(out / "fm" / "recomp_runtime.h", fm_h) &&
                    Write(out / "fm" / "recomp_runtime.c", fm_c) &&
                    Write(out / "abi5" / "recomp_runtime.h", abi5_h) &&
                    Write(out / "abi5" / "recomp_runtime.c", abi5_c) &&
                    Write(out / "abi5_rename.h", rename);
    return ok ? 0 : 1;
}
