// smoke_shl_gen: writes shl_ops.c, the emitter's translation of SHL by
// immediate (vector and scalar D) under the Hybrid export policy, for
// smoke_shl_unit to run against an independent reference.
//
// SHL was left to the JIT in Hybrid exports, so the only check of its
// translation was strict static exports running correctly. The words include
// the four that dominated the static->JIT transitions in TOTK 1.4.3.
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>

#include "core/recompiler/arm64_to_c.h"
#include "shl_words.h"

int main(int argc, char** argv) {
    if (argc != 2) {
        return 2;
    }
    // The emitter alone keeps SHL off; a Hybrid export must turn it on.
    std::string code;
    bool unhandled = false;
    suyu::recomp::Translate(kShlWords[0], 0x100, code, &unhandled);
    if (!unhandled) {
        std::fprintf(stderr, "SHL translated with g_translate_all off\n");
        return 3;
    }
    suyu::recomp::g_translate_all = suyu::recomp::TranslateAllForExport(false, false);
    if (!suyu::recomp::g_translate_all) {
        std::fprintf(stderr, "a Hybrid export leaves SHL to the JIT\n");
        return 4;
    }
    const std::filesystem::path dir = argv[1];
    std::filesystem::create_directories(dir);
    std::string out = "/* Generated by smoke_shl_gen. */\n#include \"recomp_runtime.h\"\n"
                      "#include <string.h>\n";
    std::string table = "typedef void (*ShlOpFn)(GuestContext*);\nconst ShlOpFn g_shl_ops[]={";
    for (unsigned k = 0; k < kShlWordCount; ++k) {
        code.clear();
        unhandled = false;
        if (!suyu::recomp::Translate(kShlWords[k], 0x100, code, &unhandled) || unhandled) {
            std::fprintf(stderr, "unhandled %08x\n", kShlWords[k]);
            return 5;
        }
        out += "static void op" + std::to_string(k) + "(GuestContext*c){\n" + code + "}\n";
        table += "op" + std::to_string(k) + ",";
    }
    std::ofstream(dir / "recomp_runtime.h", std::ios::binary) << suyu::recomp::RuntimeH();
    std::ofstream file(dir / "shl_ops.c", std::ios::binary);
    file << out << table << "};\n";
    return file ? 0 : 1;
}
